### ISSUE TITLE
Em Nota fiscal de entrada o sistema não converte o valor unitário ao alterar a unidade

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#101]
**Descrição**
Importar o XML de uma nota fiscal de entrada, entrar no item da nota e corrigir a UNIDADE de compra, as quantidade são convertidas corretamente, mas o VALOR UNITÁRIO continua o mesmo valor da unidade, onde o mesmo teria que divider pela quantidade convertida.

**Print**
![image](https://user-images.githubusercontent.com/53786319/63514909-b4081a80-c4b7-11e9-8a1c-a8e6f4ae21fc.png)

**Database**
Banco de dados: cidinha   CNPJ: 34156993000107

**Comment by Carlinhoslima** [comment]
Essa não conversão do valor unitário, acontece tanto na importação do XML quanto no lançamento manual, fiz o teste na tela de NOTA FISCAL DE ENTRADA da empresa demonstração, inclui o item (0082 ACUCAR UNIAO 1KG, o sistema já preencheu os campos (UNIDADE=UN; CONVERTIDO=1; PREÇO UNITARIO=5,80) alterei o campo UNIDADE para CX06, o campo CONVERTIDO mudou corretamente para 6; mas o campo PREÇO UNITARIO continuou com 5,80, esse campo PREÇO UNITARIO deveria mudar para 0,9666 (dividir o valor unitário pela quantidade convertida).

**Comment by Parapinski** [comment]
Para fazer a conversão a unidade do xml tem que ser diferente da unidade base do cadastro do item
