### ISSUE TITLE
Implementar classe fiscal de PIS e COFINS no CTe para calculo automático do imposto.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#116]
**Descrição**
Informando a classe do pis e confins não haverá necessidade do operador ficar informando manualmente a alíquota a cada operação.

**Solicitante**
S C COMERCIO E REPRESENTAÇÕES

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4141255/script.txt)
