### ISSUE TITLE
Não permitir estornar ou excluir Nota de Entrada com lote caso o lote já tenha sido movimentado. Caso não haja movimentação ao estornar ou excluir fazer o mesmo com o lote.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#123]
**Descrição**
Evitar que o controle de rastreio seja prejudicado.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3580889/script.txt)
