### ISSUE TITLE
Ao transmitir NFSe não há retorno e o sistema fica travado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#124]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
![image](https://user-images.githubusercontent.com/52629222/64081561-f3f9a980-ccd0-11e9-8c4b-2492533c29c0.png)

**Database**
automacom

**Comment by osmaroliveira** [comment]
![image](https://user-images.githubusercontent.com/52629222/64110502-59d94600-cd50-11e9-95d5-16d808c3fbc0.png)

**Comment by dziza** [comment]
Solicitar ao provedor que libere acesso para transmissão através do IP do nosso servidor 162.144.49.28
