### ISSUE TITLE
Demora excessiva para abrir tela de Pedido.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#125]
**Descrição**
Acessar tela de Pedido de Venda. Problema já ocorria antes de migrar para o novo servidor.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
cometamotos

**Comment by dziza** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3566958/script.txt)

**Comment by dziza** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3567391/script.txt)
