### ISSUE TITLE
Processo de cancelamento de NFSe não está funcionando.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#131]
**Descrição**
Ao solicitar o cancelamento de uma NFSe o sistema retorna informando que a nota não foi cancelada, porém ao verificar o site a nota está cancelada, porém não atualizou status no sistema. Teste realizado com 4 notas.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by osmaroliveira** [comment]
Mesmo problema.

**Comment by osmaroliveira** [comment]
![image](https://user-images.githubusercontent.com/52629222/66321204-39238380-e8ee-11e9-8be2-4f9d02ff944a.png)

**Comment by osmaroliveira** [comment]
O processo de cancelamento está funcionando, porém apenas o retorno em seguida do cancelamento que não. Ao consultar a nota o status é alterado para cancelado.

**Comment by ziza** [comment]
Essa tem que ser eu
