### ISSUE TITLE
Impedir a exclusão ou alteração de qualquer registro do Empenho se o status estiver diferente de Pendente.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#137]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
A validação do status é referente ao Controle de Empenho ou ao Empenho em si? "Controle de Empenho > Empenho > Item de Empenho"

**Comment by osmaroliveira** [comment]
Não permitir alteração ou exclusão dos itens e do empenho se o status do empenho estiver diferente de Pendente.

**Comment by osmaroliveira** [comment]
A alteração está sendo possível pelo grid.

**Comment by osmaroliveira** [comment]
1) Se na tela do Empenho status igual Finalizado bloquear todos os botões de edição da tela de itens.
2) Se na tela de Controle de Empenho status igual Entregue bloquear todos os botões de edição da tela de Empenho.

**Comment by Parapinski** [comment]
Bloqueado botão de limpar conforme solicitado

**Comment by osmaroliveira** [comment]
Criei novo empenho e informei dois itens. Entreguei apenas parte de um dos itens do empenho. Porém ao acessar o item não movimentado do empenho já Em Andamento consegui excluí-lo.
