### ISSUE TITLE
No Pedido de Venda, criar tela apenas para alteração do item - Considerar parâmetro Criticar Saldo do pedido.

### ISSUE THREAD

**Issue by dziza** [udisoft/roadmap#14]
**Descrição**
Verificar também que na tela de alteração de item, ao alterar a quantidade está sendo gravado a nova quantidade mesmo o sistema acusando saldo insuficiente

**Comment by Parapinski** [comment]
Implementado edição com o atalho F2

**Comment by osmaroliveira** [comment]
**Correção**
Bloquear campo lista Produto evitando alterar item da tela.

**Comment by dziza** [comment]
Bloquear alteração do produto na tela de alteração do item

**Comment by Parapinski** [comment]
Realizado correções solicitadas.
