### ISSUE TITLE
Em pedido de venda cadastro rápido de cliente obedecer as regras dos parâmetros do cadastro de pessoa.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#141]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Cometa Moto

**Comment by osmaroliveira** [comment]
Tela de cadastro rápido de pessoa não está obedecendo as regras da tela de atributos se o campo é obrigatório ou não.

**Comment by Parapinski** [comment]
Após inserir ou remover a obrigatoriedade do campo, a tela foi fechada e aberta novamente, para que assim o sistema carregue os novos parâmetros?

**Comment by osmaroliveira** [comment]
Foi sim Paulo. Acessei o cadastro de pessoaS e nos atributos mudei a obrigatoriedade do campo cnpj/cpf para não, acessei a tela de pedido e tentei cadastrar um cliente pela tela rápida.

![image](https://user-images.githubusercontent.com/52629222/65555518-e5329b00-defa-11e9-9329-753c7b2740eb.png)
