### ISSUE TITLE
Erro ao incluir nota fiscal de entrada importada pelo MONITORADOR NF-e

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#144]
Na tela do MONITORADOR NF-e, marquei uma NF-e e cliquei em IMPORTAR NF-e, fiz as correções devidas e ao clicar para incluir a NF-e, dá um erro (imagem em anexo).

![image](https://user-images.githubusercontent.com/53786319/64613636-a18d4c80-d3a4-11e9-87b0-d755f538fe8d.png)

Cliente CNPJ: 08642286000110 
NF-e: 36.419 de 07/08/19 e valor 3.726,00
Database: motonautica

**Comment by dziza** [comment]
@Parapinski backup do banco no FTP
