### ISSUE TITLE
Ao faturar pacote sem preço considerar o preço informado no cliente e ratear entre os componentes

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#145]
**Descrição**
No cadastro do produto combo ID 95 - Gestão TR tinha dois módulos COBRANÇA BANCÁRIA registrada, excluí um para que na nota não constasse duas vezes o mesmo produto. Porém agora ao tentar faturar esse cliente apresenta o erro da imagem anexada.

**Print**
![image](https://user-images.githubusercontent.com/52629222/64724550-b2bb8380-d4a0-11e9-9f9e-76dedee97db9.png)

**Database**
automacom

**Comment by dziza** [comment]
Para o rateio funcionar é necessário que todos os itens do combo esteja com valor zerado
