### ISSUE TITLE
Na capa do empenho criar campo Detalhe e enviar essa informação para as observações da NFe.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#156]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3616061/script.txt)
