### ISSUE TITLE
Corrigir status da tela Controle de Empenho quando status = Finalizado

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#160]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
![image](https://user-images.githubusercontent.com/52629222/64902252-df72c500-d671-11e9-9152-bebdeeda6ec4.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3616859/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3617097/script.txt)
