### ISSUE TITLE
Relatório de Manifestos, esta com erro de java ao imprimir.

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#166]
**Descrição**
Relatorio de Manifestos
Menu Transporte > Relatorios > Relatorio de Manifestos

**Print**
![image](https://user-images.githubusercontent.com/53625454/65042177-4f10da80-d926-11e9-9222-402f2e1190be.png)

**Database**
qualquer base

**Comment by dziza** [comment]
Será corrigido via #164
