### ISSUE TITLE
NFC-e não está imprimindo o QR Code

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#175]
**Descrição**
Entrar na tela de NOTAS FISCAIS DE SAÍDAS, buscar uma NFC-e autorizada e imprimir a mesma, verifique que as notas emitidas a partir das 15:00 horas do dia 19/09/2019, o QR Code não está saindo na impressão.

verificamos em umas 5 empresas diferentes

**Comment by dziza** [comment]
Ajustado, irá funcionar apenas para os novos documentos emitidos após a atualização
