### ISSUE TITLE
Migrar Relatório Tabela de Preços de Venda

### ISSUE THREAD

**Issue by dziza** [udisoft/roadmap#187]
Vendas > Comercial > Relatórios > Tabela de Preços de Venda

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3678502/script.txt)

**Comment by Parapinski** [comment]
[relatorio-Preco.zip](https://github.com/udisoft/roadmap/files/3678504/relatorio-Preco.zip)
