### ISSUE TITLE
Migrar Template Condicional

### ISSUE THREAD

**Issue by dziza** [udisoft/roadmap#193]
Vendas > Pedido de Venda > Impressão

**Comment by Parapinski** [comment]
Alterar código do relatório PV(1915)

**Comment by Parapinski** [comment]
[relatorio-Condicional.zip](https://github.com/udisoft/roadmap/files/3687701/relatorio-Condicional.zip)

**Comment by osmaroliveira** [comment]
Dois itens do condicional da imagem não aparecem no relatório.

![image](https://user-images.githubusercontent.com/52629222/66324279-2495ba00-e8f3-11e9-9a0a-d14d691ba0f2.png)

Base: miss

**Comment by Parapinski** [comment]
[relatorio-Condicional.zip](https://github.com/udisoft/roadmap/files/3702700/relatorio-Condicional.zip)
