### ISSUE TITLE
Na tributação, acrescentar à flag Calcula BC ICMS a opção Zerar. (zerar valores do icms importado do xml)

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#195]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by dziza** [comment]
![Sem título](https://user-images.githubusercontent.com/49871294/66309077-0faf2b80-e8df-11e9-8941-045aabcf292e.png)
