### ISSUE TITLE
No recebimento, quando tipo igual "cartão" permitir informar o código de autorização

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#198]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3736396/script.txt)
