### ISSUE TITLE
Relatório Nota Fiscal de Saída travado ao filtrar por data de referencia.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#200]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
automacom

**Comment by Parapinski** [comment]
Parâmetro para filtro de data deve estar com as seguintes referências:
data_emi_ini (para data inicial)
data_emi_fim (para data final)
