### ISSUE TITLE
Na forma de pagamento implementar flag "Solicita Nº Transação", no contas a receber implementar campo de numero da transação em cartão

### ISSUE THREAD

**Issue by dziza** [udisoft/roadmap#202]
Re. #198

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3719189/script.txt)

**Comment by osmaroliveira** [comment]
Qual o reflexo dessa flag quando igual a SIM e NÂO?

**Comment by dziza** [comment]
Quando flag = Sim obrigar preenchimento no recebimento
