### ISSUE TITLE
Controle Abertura e Fechamento de Caixa por usuário

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#203]
**Descrição**

1) Permitir amarrar no cadastro do usuário dois caixas, um sendo o Caixa Movimentação e outro sendo o Caixa Gerente. (obrigar informar o caixa gerente se o caixa movimentação for informado)

2) Se algum usuário tiver conta caixa vinculada no cadastro ele somente poderá movimentar financeiro nesta conta. 

3) Se "Movimenta Caixa Gerencial = SIM" é obrigatório abrir caixa pra movimentar financeiro.

4) Ao efetuar a abertura de caixa permitir informar valor do troco em espécie. Caso seja informado algum valor fazer lançamento a débito na conta Caixa Gerente e a crédito na conta Caixa Movimentação. (checar flag "Permite Saldo Negativo" no cadastro da conta Caixa Gerente)

5) Ao efetuar o fechamento de caixa mostrar o valor do saldo de espécie e permitir alterar. Transferir o valor informado para o Caixa Gerente realizando um lançamento a débito no Caixa Movimentação e a crédito no Caixa Gerente. (checar flag "Permite Saldo Negativo" no cadastro da conta Caixa Movimentação)

6) Não permitir movimentar financeiro com data de lançamento/baixa diferente da data de abertura do caixa.

7) Caso o usuário esqueça de fechar o caixa, no dia seguinte ao tentar movimentar financeiro o sistema deverá obrigar o fechamento do caixa aberto.

**Solicitante**
Interno

**Comment by dziza** [comment]
No usuário vincula 2 contas caixa
1 - Conta Caixa Operador
2 - Conta Caixa Gerencial

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3809403/script.txt)
