### ISSUE TITLE
Erro ao gerar Relatório de Vendas Analítico

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#207]
**Descrição**
Vendas>Relatórios

**Print**
![image](https://user-images.githubusercontent.com/52629222/66686418-67d28e80-ec4d-11e9-9695-29779be3c3b2.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by dziza** [comment]
Não conseguimos simular, favor especificar base e parâmetros onde ocorre o erro
