### ISSUE TITLE
Impressão de DACTE CT-e sem dados do ICMS

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#213]
Ao gerar o CT-e, a base de calculo e o valor do ICMS são preenchidos corretamente, aparecem normalmente no XML, mas estão aparecendo com valores ZERADOS na impressão do DACTE

Base: neguinho
ID conhecimento: 2

**Comment by dziza** [comment]
![Sem título](https://user-images.githubusercontent.com/49871294/66940548-80f78880-f01b-11e9-9912-1dbdda7148cd.png)

**Comment by dziza** [comment]
Tag ICMSSN não possui destaque da BC

**Comment by dziza** [comment]
![Sem título2](https://user-images.githubusercontent.com/49871294/66940671-bac88f00-f01b-11e9-9d09-472a3144725a.png)
DACTe do mesmo XML impresso por outros sistemas fazem dessa mesma forma
