### ISSUE TITLE
Implementar bloqueio no campo Quantidade da tela avançada do pedido de venda para impedir operador de lançar código de barras nesse campo.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#214]
**Descrição**

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by dziza** [comment]
![Sem título](https://user-images.githubusercontent.com/49871294/67008291-97efb680-f0bf-11e9-820a-b4fa40cf727b.png)

**Comment by osmaroliveira** [comment]
Aqui também.

![tambem](https://user-images.githubusercontent.com/52629222/67011706-1f3c2a80-f0be-11e9-97c1-ff9cb17d424b.png)
