### ISSUE TITLE
Produtos com movimentação de estoque sem origem

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#216]
Verificado que alguns produtos estão com MOVIMENTAÇÃO DE ESTOQUE (ID em anexo), mas não há origem dessas movimentações.

Obs: constatei que todos esses produtos é de uma única venda (ID PEDIDO DE VENDA = 1545), onde foi devolvido somente 2 produtos (ID PEDIDO DE VENDA da troca/devolução = 1676), já o sistema gerou movimentação de estoque para todos os produtos da venda origem.

Falei com o osmar sobre só excluir as movimentações, mas deixamos para fazer uma análise do que pode ter ocorrido, já que fiz um teste no sistema demonstração e não houve esse erro.

Base: dentalmaster

**Comment by Carlinhoslima** [comment]
![image](https://user-images.githubusercontent.com/53786319/67021768-21a68080-f0ce-11e9-96dc-01bf656c8c23.png)

**Comment by dziza** [comment]
Realizado cópia da base e excluído movimentação

**Comment by dziza** [comment]
@Parapinski problema parece ser no estorno do pedido, quanto tem devolução parece que o movimento não está sendo excluído

**Comment by dziza** [comment]
Excluído movimentação, não conseguimos simular, caso consigam favor descrever o passo a passo e abrir nova demanda

**Comment by Carlinhoslima** [comment]
Entrei em PEDIDO DE VENDA, na aba TROCA/DEVOLUÇÃO inclui a venda origem com todos os itens do mesma, recebi, depois estornei, exclui itens deixando somente um e recebi novamente, com isso, todos itens ficaram com movimentação de estoque de devolução.

**Comment by Parapinski** [comment]
Ajustada tela de Pedido de Venda
