### ISSUE TITLE
Colocar máscara no CEP do cadastro de empresa

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#217]
**Descrição**
Para efeito de cobrança bancária o CEP deve ser informado corretamente. Registro de boleto enviado com CEP inválido é recusado.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by osmaroliveira** [comment]
Tem algum procedimento a ser feito para o sistema validar o CEP digitado?

**Comment by osmaroliveira** [comment]
Ainda consigo informar CEP inválido.

**Comment by osmaroliveira** [comment]
O problema, aparentemente, não é apenas máscara. É impedir o cliente de digitar um CEP que não esteja na base dos correios. Como o sistema está puxando o endereço quando se digita um CEP a intenção é caso não encontre endereço algum impeça de gravar.

**Comment by Parapinski** [comment]
Implementado validação no cadastro da empresa.
