### ISSUE TITLE
Pedido de Venda com sinal de NEGATIVO (-) no campo de desconto

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#219]
Na tela de PEDIDO DE VENDA, o sistema está deixando lançar a porcentagem ou valor com o sinal NEGATIVO

![image](https://user-images.githubusercontent.com/53786319/67119581-7a9d1400-f1b5-11e9-931f-f0cc5c18a259.png)

**Database** = demonstraçao

**Comment by Carlinhoslima** [comment]
Obs: no campo ACRESCIMO tbm está aceitando

**Comment by osmaroliveira** [comment]
Na capa da tela de pedido bloquear a possibilidade de informar valor (-) no campo desconto e acréscimo de produto e serviço. Ao informar está tendo reflexo contrário ao objetivo do campo e apresenta erro ao transmitir documento fiscal.
