### ISSUE TITLE
Filtro USUARIO/OPERADOR errado no Relatorio Demonstrativo de Fechamento de Caixa

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#221]
Valores do relatório filtrado por OPERADOR está errado

Ir em VENDAS > RELATORIOS > DEMONSTRATIVO DE FECHAMENTO, escolher o período de 03/10/19 a 04/10/19, operador = MEIRE BELA VISTA

Base: meire
Filial: Bela Vista
Periodo de teste: 03/10/2019 a 04/10/2019
Operadores: MEIRE ADM e MEIRE BELA VISTA

**Comment by Carlinhoslima** [comment]
Ao gerar o DEMONSTRATIVO DE FECHAMENTO, e escolher somente um USUARIO/OPERADOR, estão saindo com a filtragem errada: tanto no resumo da forma de RECEBIMENTO quanto no detalhamento dos TITULOS RECEBIDOS, está vindo com valor total geral de todos operadores.

![image](https://user-images.githubusercontent.com/53786319/67232632-bfbc8280-f40f-11e9-9249-a2674a3f0cf2.png)

![image](https://user-images.githubusercontent.com/53786319/67232717-e2e73200-f40f-11e9-96f4-b2f6877718f9.png)

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento.zip](https://github.com/udisoft/roadmap/files/3768835/demonstrativo-de-fechamento.zip)

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento.zip](https://github.com/udisoft/roadmap/files/3769353/demonstrativo-de-fechamento.zip)

**Comment by Carlinhoslima** [comment]
Os valores da FORMA DE RECEBIMENTO e a RELAÇÃO DE TITULOS RECEBIDOS, ainda está saindo com valor total do periodo, não obedecendo o filtro por operador, na imagem em anexo coloquei um operado que não fez nada nesse período.

![image](https://user-images.githubusercontent.com/53786319/67955365-e07f9780-fbc8-11e9-80ee-5ac6a6bdcc49.png)

**Comment by Parapinski** [comment]
Carlos, veja se com esse template o filtro irá dar certo, lembrando que no cadastro do parametro dever estar como: operador

**Comment by Carlinhoslima** [comment]
verificamos, agora está filtrando corretamente, desde que esteja com o operador PREENCHIDO, se estiver em branco, os valores ficam zerados, precisamos que funcione com o operador em BRANCO também, pois a maiorias dos cliente usam ele em branco.

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento.zip](https://github.com/udisoft/roadmap/files/3821833/demonstrativo-de-fechamento.zip)
