### ISSUE TITLE
Na tela de Lote de Contas a Receber, o campo do desconto no grid não esta considerando o valor do desconto informado na tela de manutenção.

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#222]
**Descrição**
1- Na tela de Lote de Contas a Receber, pesquise pelo ID 53 e veja o grid dos títulos: 
O campo valor do desconto ficou zerado
O campo valor da baixa não diminuiu o valor do desconto

2- Na tela de contas a receber, pesquise pelos ID 323, 322 e 321
O campo desconto ficou zerado 
O campo liquidado não diminuiu o desconto

**O mesmo ocorre com a multa

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.
![image](https://user-images.githubusercontent.com/53625454/67237886-23e44400-f41a-11e9-98d3-8dd6f7367920.png)

![image](https://user-images.githubusercontent.com/53625454/67237918-3199c980-f41a-11e9-80ea-da641142e3a6.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by dziza** [comment]
Qual base?

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3772899/script.txt)
