### ISSUE TITLE
Implementar no pedido de venda bloqueio para impedir que em dois computadores alterarem a mesma venda ao mesmo tempo..

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#225]
**Descrição**
Com um pedido de venda aberto num computador é possível ir em outro computador e abrir o mesmo pedido, e em cada computador cada um fazer alterações ao mesmo tempo.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3773437/script.txt)
