### ISSUE TITLE
Relatorio KARDEX PRODUTO com saldo incorreto

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#226]
Ao gerar o relatório de kardex produto, os sistema não considera saldo anterior.

banco: pdemilho
Id produto:  4
período: 01/01/19 a 24/10/19

**Comment by Carlinhoslima** [comment]
Obs:
1-o relatório não trás o SALDO INICIAL
2-quando tem mais de uma página, o relatório NÃO considera o saldo da página anterior

**Comment by Parapinski** [comment]
[relatorio-KardexDeProduto.zip](https://github.com/udisoft/roadmap/files/3773905/relatorio-KardexDeProduto.zip)
