### ISSUE TITLE
Implementar nos itens contratados data inicio e data final.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#237]
**Descrição**
Nos itens contratados implementar data inicio e data fim. Ao buscar o cliente tanto na tela de pedido quanto na tela de emissão de pedido verificar se a data atual está compreendida entre as duas datas do item contratado, e trazer para faturamento somente os itens que atendam a essa condição. Essa implementação ajudará nos controles de cancelamento, documentos excedentes, contratos semestrais entre outas situações.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3826058/script.txt)

**Comment by osmaroliveira** [comment]
![Sem título](https://user-images.githubusercontent.com/52629222/68545477-e2eda880-03a3-11ea-8c30-7ed5bf7f2d13.png)
