### ISSUE TITLE
Implementar Relatório para Reposição de Estoque conforme exemplo anexado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#241]
[Relatorio para Reposiçao de estoque.xlsx](https://github.com/udisoft/roadmap/files/3825677/Relatorio.para.Reposicao.de.estoque.xlsx)

**Solicitante**
soumaissaude

**Comment by Parapinski** [comment]
[Relatorio_para_reposição_de_estoque.zip](https://github.com/udisoft/roadmap/files/3861053/Relatorio_para_reposicao_de_estoque.zip)

**Comment by osmaroliveira** [comment]
Relatório está trazendo itens duplicados. Testes realizados na base demo com data entre 01/09 a 30/11.

![image](https://user-images.githubusercontent.com/52629222/69152124-46698b80-0ab2-11ea-9291-0cfb314abd8e.png)
