### ISSUE TITLE
Implementar no Monitorador de NF-e opção para informar o motivo quando manifestação igual a Operação não Realizada.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#242]
**Descrição**
Para as manifestações de Operação não Realizada o governo tem até 5 anos para questionar o destinatário sobre o motivo do evento. Considerando o tempo a empresa pode não lembrar por qual motivo a operação não foi realizada e não ter como justificar.

Apresentar campo igual ocorre com a NFe ao solicitar cancelamento.
Informação não obrigatória.

**Solicitante**
Pemaza

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3869624/script.txt)

**Comment by osmaroliveira** [comment]
![Imagem](https://user-images.githubusercontent.com/52629222/69494759-b2266c80-0e95-11ea-8f30-e2008bba1f7d.png)
