### ISSUE TITLE
Nos controles de acesso criar opção para bloquear usuário impedindo-o de liquidar Titulos a Receber, Titulos a Pagar, Despesas, Receitas e Cheques.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#247]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script_middleware.txt](https://github.com/udisoft/roadmap/files/3847305/script_middleware.txt)
