### ISSUE TITLE
Erro ao imprimir MDF-e importado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#250]
**Descrição**
Após importar MDF-e ao imprimir apresenta erro da imagem.

**Print**
![image](https://user-images.githubusercontent.com/52629222/68975943-fb5a2a80-07ca-11ea-9830-b3ed90814fc0.png)

**Database**
fortferragem

**Comment by dziza** [comment]
Disparar requisição de impressão ao importar e incluir MDF-e (status Autorizado)
