### ISSUE TITLE
Implementar emissão de NF-e de NFC-e (igual ocorria com os cupons de ECF)

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#256]
**Descrição**
Implementar emissão de NF-e referenciando NFC-e´s. Isso é comum quando o cliente por exemplo pede para a empresa emitir um DANFE porque a NFC-e. Outro caso comum é quando algum cliente tem transações recorrentes durante o mês (abastecimento em postos de combustíveis) e no fim do período é emitida uma única NFe referenciando todas as NFC-e´s para que o cliente faça o pagamento.

 - Permitir parametrizar a CFOP padrão para dentro e fora do estado para essa operação.
 - Permitir selecionar vários NFC-e´s apenas de um mesmo cliente.
 - Permitir informar o cliente quando as NFC-e´s selecionadas foram emitidas para consumidor final.
 - Não permitir alterar cliente quando a NFC-e capturada estiver vinculada há alguma pessoa.
 
* Implementação atenderá operação comum nos postos de combustíveis.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3962604/script.txt)
