### ISSUE TITLE
No botão Imprimir do Contas a Receber disponibizar relatório de Fatura quando Origem do título for igual Fatura.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#257]
**Descrição**
Na template de Fatura possibilitar imprimir analítico e sintético, sendo o analítico por venda e o sumarizado por item.

**Solicitante**
FortFerragens

**Comment by Parapinski** [comment]
[Relatorio_Fatura_Cliente.zip](https://github.com/udisoft/roadmap/files/3897913/Relatorio_Fatura_Cliente.zip)

**Comment by Parapinski** [comment]
Ajusta linha 322 (TituloRecCrud) de acordo com a Categoria cadastrada para a Fatura.

**Comment by osmaroliveira** [comment]
Após liberar relatório nos módulos e liberar no usuário mesmo assim a fatura não aparece no botão imprimir.
