### ISSUE TITLE
Implementar possibilidade de finalizar venda quando Troca/Devolução ficar com valor zerado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#258]
**Descrição**
Quando o item devolvido/trocado tem o mesmo valor do item vendido o pedido fica com valor zerado impedindo o recebimento e consequentemente a impressão das notas fiscais.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
Teste realizado Pedido finalizado com valor zerado e XML validado
![image](https://user-images.githubusercontent.com/19494137/69440403-8b4a2800-0d27-11ea-9ea3-2012eb0fbba8.png)
![image](https://user-images.githubusercontent.com/19494137/69440456-a3ba4280-0d27-11ea-92c6-a91ac8f6c824.png)

**Comment by Parapinski** [comment]
Teste realizado com devolução, pedido finalizado e XML validado.
