### ISSUE TITLE
Ao gerar o contas a receber setar o tipo de cobrança vinculado na conta bancária da forma de pagamento que originou o titulo

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#259]
**Descrição**
Atualmente é necessário informar no cadastro do cliente o tipo de cobrança - por exemplo Cobrança Bancária - para que se possa gerar o boleto. Como sugestão de fluxo, caso não exista essa informação no cadastro do cliente pegar o tipo de cobrança do banco informado na forma de pagamento.

Caso haja mais de um banco informado na forma de pagamento possibilitar escolher o banco.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3974552/script.txt)

**Comment by osmaroliveira** [comment]
1) Mesmo informando dois bancos na forma de pagamento com tipo Boleto Bancário, e na venda ao receber como boleto escolher o banco o Udisys está gerando o boleto sempre para o primeiro banco registrado na forma de pagamento.

2) Mesmo tendo dois bancos informados na forma de pagamento, o Udisys não está obrigando escolher um banco ao receber por boleto.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4030598/script.txt)
