### ISSUE TITLE
No Monitorador de NF-e tratar os eventos vinculados às notas capturadas. 

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#262]
**Descrição**
Tratar o evento Cancelado apresentando a nota como cancelada, trazer o motivo do cancelamento. Impedir a nota de ser impressa ou baixar xml.
Tratar o evento Ciência da Operação. Setar esse evento no registro.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
Em pesquisa no manual da Sefaz e testes, não localizada retorno do status do Evento Ciência da Operação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3926804/script.txt)

**Comment by osmaroliveira** [comment]
Emiti uma nota fiscal da Udisoft para o cliente Pemaza e cancelei em seguida, consultei no monitor e o registro foi capturado no grid errado e sem as informações solicitadas.


![image](https://user-images.githubusercontent.com/52629222/70527046-5577b280-1b21-11ea-8bec-5c4b96911050.png)

**Comment by Parapinski** [comment]
Se o cancelamento ocorreu segundos/minutos antes a consulta, pode haver um delay para que a informação seja disponibilizada em Ambiente Nacional. Se possível, consulte novamente na sefaz, e realize a consulta pela data.

**Comment by osmaroliveira** [comment]
Paulo, o cancelamento foi realizado ontem logo após a emissão da nota. Mesmo consultando hoje não puxa o evento e o registro se mantém no grid de cima.

![image](https://user-images.githubusercontent.com/52629222/70581353-51817a00-1b8d-11ea-95c5-8f6ec57969ad.png)

**Comment by osmaroliveira** [comment]
Os registros que são capturados com Tipo = Completo devem vir também com o ultimo evento vinculado para o operador saber qual Manifestação realizar em seguida.

![image](https://user-images.githubusercontent.com/52629222/71767315-9032f780-2ee1-11ea-958e-72717b4b2ec7.png)

**Comment by ziza** [comment]
Não compilou com a pcnConversao e pcnRetDistDFeInt disponibilizadas
