### ISSUE TITLE
Ajustes módulo Fechamento de Caixa

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#266]
**Descrição**
1) Em Resumo das Saídas acrescentar a rubrica Títulos Recebidos e totalizar os títulos recebidos pelo operador. E na aba Vendas acrescentar sub-aba Títulos Recebidos.
2) Ao Fechar o Caixa e informar o Troco Final, o sistema deve levar em consideração o saldo da rubrica Dinheiro do Resumo de Entrada. Sendo assim, o valor do Troco Final é = valor informado do troco final (-) dinheiro do Resumo de Entrada.
3) Não permitir Conciliação de Caixa ou Banco quando o registro a ser conciliado esteja vinculado a um caixa não confirmado. Emitir mensagem "Registro vinculado a caixa não confirmado. Aguardar confirmação".

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4111672/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4216167/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4216480/script.txt)
