### ISSUE TITLE
Saldo de estoque errado no cadastro de item

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#269]
Cliente importou uma nota de entrada (ID 1290), com isso cadastrou automaticamente um item novo (ID 5634), após finalizar a nota, cliente percebeu que havia lançado esse item errado, voltou na nota, tirou esse item e colocou o item correto e salvou a nota.
Com isso, o item (ID 5634) ficou com saldo de estoque errado na tela do cadastro do item, mas nos relatório de saldo de estoque, kardex item e nem na movimentação de estoque, consta essas informações.

Cliente CNPJ: 19540824000182
Banco dados: cometamotos

![nota entrada](https://user-images.githubusercontent.com/53786319/69815995-e5d30080-11cd-11ea-8e22-1dbbb620a4f4.jpg)
![produto](https://user-images.githubusercontent.com/53786319/69816005-eb304b00-11cd-11ea-96cc-c0d7f2d903db.jpg)

**Comment by Carlinhoslima** [comment]
Fiz o teste na empresa DEMONSTRAÇÃO, dei entrada na NF-e (ID 276), cadastrou os produtos, voltei na nota e alterei o item ID 129 pelo ID 123, salvei a nota, veja que no item 129, ainda tem o saldo de estoque 1, mas não tem a origem desse saldo.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3934504/script.txt)
