### ISSUE TITLE
Mesmo configurando o item de uso e consumo sistema não faz a substituição quando importa nota de despesa, APENAS QUANDO UTILIZADO NOP NO DEPARA

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#271]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by ziza** [comment]
Não consegui simular, favor descrever o passo a passo informando base, nop, numero da nota e item utilizados

**Comment by ziza** [comment]
Ajustado
