### ISSUE TITLE
Os títulos a pagar gerados pela tela de capitação de recursos estão ficando com tipo em branco

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#273]
**Descrição**
Os títulos a pagar gerados pela tela de captação de recursos, estão ficando com o campo TIPO em branco.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.
![image](https://user-images.githubusercontent.com/53625454/69829385-1c247600-11f6-11ea-8c19-6b497d492bc6.png)

**Database**
soumaissaude

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3906184/script.txt)

**Comment by Parapinski** [comment]
Adicionado campo Tipo no cadastro de Tipo de Captação. Possibilitando assim informar a forma de Pagamento que será utilizada nas parcelas da captação.
