### ISSUE TITLE
Saldo de estoque ficando no almoxarifado errado ao excluir item de condicional

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#275]
**Descrição**
Ao excluir item da condicional o saldo do estoque, deste item, não esta retornando ao almoxarifado de origem

Exemplo da condicional ID 719, fiz a exclusão do item AGUA MINERAL GALAO DE 20 LITROS e o saldo do estoque não retornou ao almoxarifado central

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.
![image](https://user-images.githubusercontent.com/53625454/69983443-13d97d00-150d-11ea-9808-1b824c956bf1.png)

![image](https://user-images.githubusercontent.com/53625454/69983734-cc9fbc00-150d-11ea-9202-62f96e822cef.png)

![image](https://user-images.githubusercontent.com/53625454/69983748-d5908d80-150d-11ea-969f-ee63f3f477b2.png)

**Database**
onysion_demo

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3929980/script.txt)
