### ISSUE TITLE
Tratar tributação padrão quando o xml não vier com tag de tributação e o item não tenha cadastro/tributação no Emsys.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#277]
**Descrição**
Pegamos na rede planalto um xml que não tinha informação de IPI para ser tratado no depara, e no emsys não tinha cadastro do item. Potanto, não tinha como tratar a tributação do IPI e na nota importada o item ficava sem essa tributação forçando o operador e editar todos os itens e amarrar manualmente.

**Solicitante**
Rede Planalto

**Comment by ziza** [comment]
Implementado no de/para, basta deixar todas as demais opções como "Todos" e informar a tributação de entrada
