### ISSUE TITLE
Ajustar tratamento código referência fornecedor.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#278]
**Descrição**
Quando cliente muda informação de referencia de fornecedor no item do Emsys estamos tendo que acessar a base do importar e corrigir campo produto para que o item seja importado corretamente.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by ziza** [comment]
Implementado opção para selecionar o produto sem necessidade de alterar codigo no emsys
![Anotação 2019-12-06 214532](https://user-images.githubusercontent.com/49871294/70365770-e3c60d00-1871-11ea-971e-f4f283e8120c.png)
