### ISSUE TITLE
Ao excluir um item do pedido condicional esse item também está sendo excluído da aba Complemento/Condicional. Manter o item.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#286]
**Descrição**
Uma vez um condicional criado, ao excluir esse item da grid Produtos / Serviço, esse item deve ser mantido no aba Condicional.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3969710/script.txt)
