### ISSUE TITLE
Quando xml vem com a tag de pagamento informado a vista (dinheiro) e na capa da nota se altera o pagamento para parcelado o sistema apresenta erro de "INTERNAL ERROR null" conforme imagem.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#291]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by ziza** [comment]
![WhatsApp Image 2019-12-11 at 12 09 41](https://user-images.githubusercontent.com/49871294/70710610-4d08ae80-1cbe-11ea-93e2-17cbb626c441.jpeg)
