### ISSUE TITLE
Implementar no cadastro do emitente, para a data de entrada da nota, o mesmo recurso de "Prazo em Dias p/ o Vencimento do Contas a Pagar"

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#293]
**Descrição**
Se no campo deixar zero a data de entrada será a mesma da emissão.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by ziza** [comment]
Opção no emitente para adicionar um nº de dias na data de entrada da nota
