### ISSUE TITLE
Testar conversão de unidade ao importar a nota 330471 do cliente MRA IV - Base PCP

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#296]
**Descrição**
Custo do item 4712 ficou com valor unitário igual valor total

**Print**
![imagem](https://user-images.githubusercontent.com/52629222/70832018-6ac33a00-1dca-11ea-928f-fb70b5076706.jpeg)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by ziza** [comment]
![1](https://user-images.githubusercontent.com/49871294/70853372-f94bc000-1e8b-11ea-85e6-ceebdde528d6.png)
![2](https://user-images.githubusercontent.com/49871294/70853373-f94bc000-1e8b-11ea-8b06-08e8564772e3.png)

**Comment by ziza** [comment]
Está convertendo corretamente
