### ISSUE TITLE
Implementar data de vencimento da licença no item e exibir só pra base udisof.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#300]
**Descrição**
Considerar sempre a data final do primeiro registro.

**Comment by osmaroliveira** [comment]
Vamos ter que pensar melhor sobre esse recurso. Temos duas situações, se utilizarmos a data final como controle do vencimento da licença teremos problemas com os itens que devem ser cobrados apenas uma vez.

**Comment by osmaroliveira** [comment]
Implementar data de vencimento da licença no item e exibir só pra base udisof.

**Comment by ziza** [comment]
Colocar "Data de Bloqueio" pra não confundir com as demais datas dessa tela

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4010567/script.txt)
