### ISSUE TITLE
Implementar no CT-e flag de substituição de tomador para atender quando um CTe de substituição tem como alteração o tomador.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#308]
**Descrição**
A alteração do tomador é possível quando: 

O Emitente informar um tomador incorreto, porém existente;
O Tomador incorreto deverá, em resposta, gerar o evento " Prestação de serviço em desacordo ";
Isso possibilita que o Emitente gere um CT-e de Anulação  
Em seguida, o Emitente poderá emitir um CT-e de Substituição  (Tipo do CT-e = 3), informando um novo tomador de serviço.

A NT apresenta as novas Regras de Validação (Rejeições) relacionadas a este processo:

Rejeição 738 
Regra de Validação : Se Tipo do CT-e=3 (Substituição) e informado toma3 sem informar indicador de alteração de tomador <indAlteraToma> ” 
Mensagem: “A marcação do tomador do CT-e substituto deve ser igual a informada no CT-e substituído.”
Explicação:  Essa rejeição acontecerá caso o usuário não preencha a tag que indica a alteração do tomador. Ela existe porque o usuário pode emitir um CT-e de Substituição por outros motivos, mantendo o mesmo tomador (destinatário). O Webservice entenderá que este é o caso, a não ser que preencha o campo  <indAlteraToma> .
Rejeição 552
Regra de Validação : Se Tipo do CT-e=3 (Substituição) e informado toma4 sem informar indicador de alteração de tomador <indAlteraToma> ;
Mensagem: “CNPJ/CPF do tomador do CT-e substituto deve ser igual ao informado no CT-e substituído ”
Explicação:  Essa rejeição acontecerá caso o usuário não preencha a tag que indica a alteração do tomador. Ela existe porque o usuário pode emitir um CT-e de Substituição por outros motivos, mantendo o mesmo tomador (destinatário). O Webservice entenderá que este é o caso, a não ser que preencha o campo  <indAlteraToma> .
Rejeição 558
Regra de Validação : Se Tipo do CT-e=3 (Substituição) e estiver informado toma4 sem informar indicador de alteração de tomador <indAlteraToma> ;
Mensagem: “IE do tomador do CT-e substituto deve ser igual ao informado no CT-e substituído​”
Interpretação (TecnoSpeed) :   Essa rejeição acontecerá caso o usuário não preencha a tag que indica a alteração do tomador. Ela existe porque o usuário pode emitir um CT-e de Substituição por outros motivos, mantendo o mesmo tomador (destinatário). O Webservice entenderá que este é o caso, a não ser que preencha o campo  <indAlteraToma> .
Rejeição 739
Regra de Validação : Se Tipo do CT-e=3 (Substituição) e informado indicador de alteração de tomador <indAlteraToma>;
Mensagem: “ O CT-e substituído deve possuir evento de Prestação do Serviço em Desacordo”
Interpretação (TecnoSpeed) :   Conforme explicado no processo de alteração, o tomador incorreto deve emitir um evento de "Prestação de Serviço em Desacordo" para que o emitente possa emitir um CT-e de Substituição alterando o tomador.
Rejeição 740
Regra de Validação : Se Tipo do CT-e=3 (Substituição), informado indicador de alteração de tomador <indAlteraToma> e informado toma4;
Mensagem: “O CNPJ base do tomador informado deve estar relacionado no CT-e substituído como um dos papéis existentes (remetente, destinatário, recebedor, expedidor ou toma4)”
Interpretação (TecnoSpeed) :  Assim como em qualquer CT-e, 
Rejeição 741
Regra de Validação : Se Tipo do CT-e=3 (Substituição), informado indicador de alteração de tomador <indAlteraToma> e informado toma4:;
Mensagem: “A UF do tomador informado deve a mesma do tomador informado no CT-e substituído ”
Interpretação (TecnoSpeed) :   Como o próprio Ajuste Sinief 08/17 institui, só é possível realizar a alteração do tomador caso ele seja da mesma UF do tomador incorreto.
Rejeição 742
Regra de Validação : Se Tipo do CT-e=3 (Substituição), informado indicador de alteração de tomador <indAlteraToma> e informado toma3;
Mensagem: “O tomador indicado no CT-e substituto deve ser diferente do indicado no CT-e substituído ”
Interpretação (TecnoSpeed) :  Ocorre quando o emitente tenta enviar o CT-e de Substituição com o mesmo tomador incorreto do CT-e original. Serve para previnir que ele precise substituir novamente.

**Solicitante**
Osvair

**Comment by ziza** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3995598/script.txt)

**Comment by ziza** [comment]
@Parapinski criar a flag na aba "Substituição", default "Não", o campo já foi criado nas bases.
