### ISSUE TITLE
Ajuste ao lançar Saldo Inicial no cadastro de contas Caixa e Banco

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#311]
**Descrição**
1) Ao informar saldo inicial gerar registro de movimentação com data anterior ao primeiro registro da conta, ou uma data fixa por exemplo 01/01/1980.
2) Gerar registro já conciliado na mesma data do movimento.

![image](https://user-images.githubusercontent.com/52629222/71519146-8e878500-288c-11ea-9d8c-bc97f5e453be.png)

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4016751/script.txt)
