### ISSUE TITLE
Em Emissao de Pedidos em lote sistema não está considerando a quantidade informado no item contratado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#315]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by ziza** [comment]
Duplicado com #317
