### ISSUE TITLE
Ao faturar pedido da MEIRE (19614810000166) o sistema está puxando valor de quase o dobro. Procurei identificar mas não consegui.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#317]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
udisoft

**Comment by ziza** [comment]
- O problema é na tela de pedido de venda, ao selecionar o pacote vinculado no cliente

**Comment by osmaroliveira** [comment]
No pedido de venda, ao selecionar o cliente, udisys não está trazendo a tela de itens contratados, sendo assim não consigo testar a demanda.

**Comment by osmaroliveira** [comment]
![image](https://user-images.githubusercontent.com/52629222/72204270-59626180-344c-11ea-915a-c596dac32ce2.png)

![image](https://user-images.githubusercontent.com/52629222/72204297-9af30c80-344c-11ea-83f6-b9516f80f591.png)
