### ISSUE TITLE
Erro no Gerenciador de Notas Eletronicas ao consultar nota já Autorizada.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#321]
**Descrição**
Ao consultar uma nota já Autorizada o Udisys está retornando mensagem: Rejeição: NF-e não consta na base da Sefaz, e retorna essa nota para a situação de Pendente. Porém, se consulto essa mesma nota na base produção o retorno é outro e a nota se mantem como Autorizada.

**Print**
![image](https://user-images.githubusercontent.com/52629222/71765551-b1d5b400-2ecc-11ea-91ad-38a8b06561f6.png)

**Database**
base meire usada para teste

**Comment by Parapinski** [comment]
Notas emitidas em ambiente de produção não constam em ambiente de homologação. Por este motivo quando se pesquisa em ambiente de homologação retorna esta mensagem, por serem ambientes distintos.
