### ISSUE TITLE
Relatorio Tabela de Preco de Venda esta trazendo preço em branco

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#326]
**Descrição**
Relatorio Tabela de Preco de Venda esta trazendo preço em branco, quando a quantidade minima informada no cadastro da tabela de preço, no campo Qtd. Min esta maior que 1.

Anexo imagem do relatório com item TIRAS GLICEMIA SENS, onde deixei o campo Qtd. Min com 1 (aparece o preço) e o outro com 5 (nao aparece o preço).
**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.
![image](https://user-images.githubusercontent.com/53625454/72106584-02eb0b00-3306-11ea-98b7-d2f7425973fa.png)

**Database**
soumaissaude

**Comment by Parapinski** [comment]
[tabela-de-precos-de-venda.zip](https://github.com/udisoft/roadmap/files/4055497/tabela-de-precos-de-venda.zip)
