### ISSUE TITLE
Na tela de emissão de pedido em lote, ao gerar pedido com quantidade maior que 1, apesar do total dos serviços estar correto, o total do pedido fica errado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#327]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
![image](https://user-images.githubusercontent.com/52629222/72204556-c0cde080-344f-11ea-99f0-56d58bab574f.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4056016/script.txt)
