### ISSUE TITLE
Negociação de Preço para o tipo Fixo não esta sendo considerado na tela de pedido de venda

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#329]
**Descrição**
Tela de pedido de venda não esta considerando a configuração da Tabela de Preço para um item especifico negociado com Tipo Preco = Fixo

Feito teste na base onysion_demo

**Print**

![image](https://user-images.githubusercontent.com/53625454/72616420-48629600-390d-11ea-84ed-ce1c8fb665e6.png)

![image](https://user-images.githubusercontent.com/53625454/72616471-6c25dc00-390d-11ea-83fd-dc8145e1ce5e.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by osmaroliveira** [comment]
Problema ainda continua.
