### ISSUE TITLE
Na lista de pessoas do contas a receber possibilitar habilitar mais colunas de pesquisa.

### ISSUE THREAD

**Issue by Raphaelrddf** [udisoft/roadmap#33]
**Correção**
Na lista de pessoas dos títulos quando setado cidade está vindo o ID e não o nome.

**Descrição**
Inserir o campo de ID nos campos de Contas a Receber e Pagar o mesmo so possui o NOME DA PESSOA.

**Comment by osmaroliveira** [comment]
Criar em parâmetro lista de opções assim como o pedido de venda.

**Comment by osmaroliveira** [comment]
**Correção**

Na lista de pessoas dos títulos quando setado cidade está vindo o ID e não o nome.

**Comment by Parapinski** [comment]
Ajustado lista de pessoas para apresentar o nome da cidade
