### ISSUE TITLE
Implementar flag para possibilitar gerar Centro de Resultado ao cadastrar item Espécie = Veículo.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#330]
**Descrição**
Minha sugestão é que na aba Dados do Veículo seja criado uma flag "Gera Centro de Resultado", e que esse campo esteja disponivel nos parâmetros da tela para ser definido como padrão SIM ou NÂO.

Para gerar a descrição do Centro de Resultado utilizar o campo descrição do item.

**Solicitante**
Empresa Luiz Gustavo

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4100394/script.txt)
