### ISSUE TITLE
Implementar controle de Vale de Funcionário

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#339]
**Descrição**
Criar tela de controle.

1) Campos: Seleção de funcionários, Data do vale, Seleção das contas caixas e bancos, Valor, Detalhe.

2) Ao inserir registro gerar lançamento negativo no caixa ou banco escolhido; gerar lançamento positivo na tela de controle do funcionário. Verificar flag "permite saldo negativo" no cadastro dos caixas/bancos.

3) Apresentar campo Saldo com o saldo total dos vales.

4) Nessa mesma tela disponibilizar botão Liquidar onde será possível fazer o acerto do vale. 

5) Permitir/exigir selecionar os vales que serão liquidados.

6) Permitir liquidação parcial dos vales selecionados, porém não inferior a somatória total - o valor do menor vale.

7) Na tela de recebimento liberar apenas opção para liquidação em Dinheiro ou Banco.

8) Ao liquidar gerar lançamento positivo no banco/caixa escolhido e negativo na tela do funcionário.

9) Criar aba Vales liquidados e transferir para essa aba os vales liquidados.

10) Permitir estorno de liquidação. Criticar se os lançamentos não estão consolidados.

11) No Fechamento de Caixa ao confirmar um caixa com rateio de diferença gerar lançamento para o funcionário.

12) Possibilitar imprimir relatório filtrando por funcionário e datas. Se não informar funcionário imprimir de todos com movimentação no período selecionado. (Campos: Data, Valor, Detalhe e Origem.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4275841/script.txt)

**Comment by Parapinski** [comment]
Parametros:
data_ini  Date 
data_fim  Date
funcionario  Integer Default: 0
[relatorio_vale_funcionario.zip](https://github.com/udisoft/roadmap/files/4276944/relatorio_vale_funcionario.zip)
