### ISSUE TITLE
No DRE Sintético contemplar as notas fiscais de origem manual que tenham NOP que gera financeiro

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#341]
Administrativo > Relatórios > DRE Sintético

**Comment by Parapinski** [comment]
[dre-sintetico.zip](https://github.com/udisoft/roadmap/files/4182803/dre-sintetico.zip)

**Comment by Parapinski** [comment]
[dre-sintetico.zip](https://github.com/udisoft/roadmap/files/4215611/dre-sintetico.zip)
