### ISSUE TITLE
No DRE Analítico p/ Rubrica contemplar as notas fiscais de origem manual que tenham NOP que gera financeiro

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#342]
Administrativo > Relatórios > DRE Analítico p/ Rubrica

**Comment by Parapinski** [comment]
[dre-analitico-p-rubrica.zip](https://github.com/udisoft/roadmap/files/4186003/dre-analitico-p-rubrica.zip)

**Comment by Parapinski** [comment]
[dre-analitico-p-rubrica.zip](https://github.com/udisoft/roadmap/files/4215725/dre-analitico-p-rubrica.zip)
