### ISSUE TITLE
No DRE Analítico p/ Lançamento contemplar as notas fiscais de origem manual que tenham NOP que gera financeiro

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#343]
Administrativo > Relatórios > DRE Analítico p/ Lançamento

**Comment by Parapinski** [comment]
[dre-analitico-p-lancamento.zip](https://github.com/udisoft/roadmap/files/4186829/dre-analitico-p-lancamento.zip)

**Comment by Parapinski** [comment]
[dre-analitico-p-lancamento.zip](https://github.com/udisoft/roadmap/files/4215753/dre-analitico-p-lancamento.zip)
