### ISSUE TITLE
No Relatório de Vendas p/ Cliente contemplar as notas fiscais de origem manual que tenham NOP que gera financeiro

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#344]
Vendas > Relatórios > Relatório de Vendas p/ Cliente

**Comment by Parapinski** [comment]
[relatorio-de-vendas-p-cliente.zip](https://github.com/udisoft/roadmap/files/4187292/relatorio-de-vendas-p-cliente.zip)

**Comment by Parapinski** [comment]
[relatorio-de-vendas-p-cliente.zip](https://github.com/udisoft/roadmap/files/4216010/relatorio-de-vendas-p-cliente.zip)
