### ISSUE TITLE
Implementar DRE de Veículo

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#345]
**Descrição**
Considerar o custo do veículo informado no cadastro do produto; o lucro bruto calculado pela venda - o custo; e todas as despesas lançadas no centro de resultado desse veículo; e no final apresentar o lucro liquido.

**Solicitante**
Rofe

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4206010/script.txt)

**Comment by Parapinski** [comment]
[dre-veiculo.zip](https://github.com/udisoft/roadmap/files/4206074/dre-veiculo.zip)

**Comment by Parapinski** [comment]
parâmetro: veiculo (id do produto)
