### ISSUE TITLE
Implementar Relatórios de Contrato conforme os modelos anexados

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#348]
[CONTRATO  VENDA.pdf](https://github.com/udisoft/roadmap/files/4187265/CONTRATO.VENDA.pdf)
[CONTRATO COMPRA.pdf](https://github.com/udisoft/roadmap/files/4187267/CONTRATO.COMPRA.pdf)
[CONTRATO CONSIGNAÇÃO.pdf](https://github.com/udisoft/roadmap/files/4187269/CONTRATO.CONSIGNACAO.pdf)

**Solicitante**
Rofe

**Comment by Parapinski** [comment]
[ContratoConsignado.zip](https://github.com/udisoft/roadmap/files/4232400/ContratoConsignado.zip)
Parametros:
- veiculo (Integer) - Default: 0 - Obrigatório
- contrato (String)
- pessoa (Integer) - Default: 0 - Obrigatório
- km (String)
- renavam (String)
- comissao (Numeric)

**Comment by Parapinski** [comment]
[ContratoConsignado.zip](https://github.com/udisoft/roadmap/files/4232509/ContratoConsignado.zip)

Parametros:

veiculo (Integer) - Default: 0 - Obrigatório
contrato (String)
pessoa (Integer) - Default: 0 - Obrigatório
km (String)
renavam (String)
comissao (Numeric)

**Comment by Parapinski** [comment]
[ContratoCompra.zip](https://github.com/udisoft/roadmap/files/4232663/ContratoCompra.zip)

Parametros:

veiculo (Integer) - Default: 0 - Obrigatório
contrato (String)
km (String)
renavam (String)
vendedor (Integer) - Default: 0 - Obrigatório
placa (String)
preco (Numeric)
condicao (String)
tipo_venda (String)
nome_vendedor (String)

**Comment by Parapinski** [comment]
[ContratoVenda.zip](https://github.com/udisoft/roadmap/files/4232709/ContratoVenda.zip)

Parametros:

veiculo (Integer) - Default: 0 - Obrigatório
contrato (String)
km (String)
renavam (String)
comprador (Integer) - Default: 0 - Obrigatório
placa (String)
preco (Numeric)
condicao (String)
tipo_venda (String)
nome_vendedor (String)
