### ISSUE TITLE
Nota ficar em destaque para todos usuários ao estar sendo lançada

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#360]
Devido a todos do departamento terem acesso a importação autorizada, sinalizar quando alguem estiver lançando a nota. Segue print com a ideia de deixar marcado para todos os usuarios o flag destacado no 
print.

Décio - Pamela

**Comment by Carlinhoslima** [comment]
![image](https://user-images.githubusercontent.com/53786319/74938260-0a510a00-53c4-11ea-856b-7bb323a8e4d6.png)

**Comment by ziza** [comment]
1 Dia

**Comment by ziza** [comment]
2 Dias
