### ISSUE TITLE
Erro de arredondamento de rateio de despesa

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#362]
Segue erro de arredondamento de rateio de despesa, o que esta impossibilitando de importar a nota fiscal para o EMSYS.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.
![image](https://user-images.githubusercontent.com/53786319/74939213-e393d300-53c5-11ea-882a-557a655e7491.png)

**Database**
Decio Holding

**Comment by ziza** [comment]
Essa nota em específico não tem como lançar no nfast pois é feito rateio de um mesmo item em mais de um tipo de despesa, neste caso tem que aguardar a finalização da demanda #356
