### ISSUE TITLE
A data da baixa, na tela de Contas a Pagar, esta ficando em branco quando o titulo é liquidado pela tela de lote

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#364]
**Descrição**
Menu Financeiro > Contas a Pagar > Lote Conta a Pagar
-Gerei lote ID 7 dos conta a pagar ID 58 e 59
-Liquidei na data 26/02

Ao acessar os titulos ID 58 e 59 no menu Financeiro > Contas a Pagar > Contas a Pagar
- O campo Data da baixa esta em branco

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.
![image](https://user-images.githubusercontent.com/53625454/75354201-fce3c600-5882-11ea-9343-8b77b8a20787.png)

![image](https://user-images.githubusercontent.com/53625454/75354844-01f54500-5884-11ea-8d1e-1abad2ed08bd.png)

**Database**
onysion_demo

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4281917/script.txt)
