### ISSUE TITLE
Implementar no NFAST opção para exportar as informações da nota fiscal para uma planilha e poder baixá-la, da mesma forma que é feito no Tributum (modelo da planilha em anexo)

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#367]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Pamela Décio

**Comment by osmaroliveira** [comment]
[Tributum - Ítens da NFe.xlsx](https://github.com/udisoft/roadmap/files/4261551/Tributum.-.Itens.da.NFe.xlsx)

**Comment by ziza** [comment]
![image](https://user-images.githubusercontent.com/49871294/75549984-a5bf2c00-5a0f-11ea-882e-613b48f48dee.png)

**Comment by ziza** [comment]
Isso já foi feito, conforme imagem acima, e já foi validado pela Débora.
No mesmo modelo do tributum não tem como.
