### ISSUE TITLE
Ajustes tela de Fechamento de Caixa

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#369]
**Descrição**
1) Alterar descrição da rubrica de saída Contas a Receber para Titulos Recebidos.
2) Ao clicar sobre a rubrica ir para a tela de Titulos Recebidos.
3) Na tela de Títulos Recebidos ao maximizar a tela de Fechamento de Caixa expandir as colunas.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by ziza** [comment]
3 - Na tela de Títulos Recebidos ao maximizar a tela de Fechamento de Caixa expandir as colunas.
Essa não tem como fazer.

**Comment by osmaroliveira** [comment]
Não tem como ficar como essa tela?
![image](https://user-images.githubusercontent.com/52629222/75591384-fa859580-5a55-11ea-8601-0045c4a1aa78.png)

Essa dos títulos fica assim.
![image](https://user-images.githubusercontent.com/52629222/75591447-230d8f80-5a56-11ea-89ce-a422dd133869.png)

**Comment by ziza** [comment]
Não tem como mudar o tamanho das colunas quando maximiza a tela, esses tamanhos são fixos, o grid só permite tamanho dinamico em uma coluna, não em todas
