### ISSUE TITLE
Erro ao confirmar Fechamento de Caixa com ajuste de quebra informado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#370]
**Print**
![image](https://user-images.githubusercontent.com/52629222/75486258-8c23d300-5982-11ea-853a-4a6f796466a7.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
Script de correção na Issue #339
