### ISSUE TITLE
Divergencia de relatorio de DEMONSTRATIVO DE FECHAMENTO e RELATORIO DE VENDA P/ VENDEDOR quando há TROCA de mercadoria.

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#373]
No dia 16/01/20 foi efetuado uma venda de R$ 251,00 (ID 375), ao gerar o DEMONSTRATIVO DE FECHAMENTO nos totalizadores os valores estão corretos, mas nos valores detalhados está faltando um valor de R$ 84,42. Essa diferença é referente a uma troca efetuada no dia 29/01/20 (ID 501), essa devolução não deveria faezer nenhum efeito no dia 15/01, mas está fazendo efeito tanto no DEMONSTRATIVO DE FECHAMENTO quanto no RELATORIO DE VENDA P/ VENDEDOR.

Já no dia 29/01/20, onde ouve a troca, o relatorio de VENDAS P/ VENDEDOR não está computando os produtos vendidos e nem o abatimento do produto devolvido.

Database: martinelli

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento.zip](https://github.com/udisoft/roadmap/files/4293089/demonstrativo-de-fechamento.zip)

**Comment by Parapinski** [comment]
[relatorio-de-vendas-p-vendedor.zip](https://github.com/udisoft/roadmap/files/4293128/relatorio-de-vendas-p-vendedor.zip)

**Comment by Parapinski** [comment]
[relatorio-de-vendas-p-vendedor.zip](https://github.com/udisoft/roadmap/files/4294257/relatorio-de-vendas-p-vendedor.zip)
