### ISSUE TITLE
Ajustes no tratamento da Tabela de Preços

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#379]
**Descrição**
1) Na tela de Preços, criar flag para o operador escolher se o valor a ser descontado/acrescido se é para ser apresentado como desconto ou acréscimo na venda ou se altera o preço.

2) Na tela de Preços, criar flag "Sim/Não" para permitir desconto no pedido de venda sobre a tabela. Se "Sim" informar ao operador que o desconto dado manualmente no item irá substituir o desconto da tabela.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4309309/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4309574/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4372026/script.txt)

**Comment by osmaroliveira** [comment]
Acrescentar na flag "Permite Outros Descontos" opção "Substituir desconto". Ao selecionar essa opção o desconto informado no pedido deverá substituir o desconto da tabela se houver e emitir mensagem ao operador que o desconto informado irá sobrepor o desconto da tabela. Lembrando sempre que apenas se houver desconto ou acréscimo. Uma sugestão seria de habilitar esse campo apenas se houve alguma informação de desconto/acrescimo.

**Comment by Parapinski** [comment]
Aberta Issue #406 para a nova implementação.

**Comment by osmaroliveira** [comment]
Desconto não está destacando.

![image](https://user-images.githubusercontent.com/52629222/77862342-c7ffc180-71e8-11ea-8cb0-b5528e19f321.png)
