### ISSUE TITLE
Vincular na aba Veículos do cadastro do produtos as tabelas Marca e Modelo do TR como acontece com Combustível e Tipo.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#392]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4312680/script.txt)
