### ISSUE TITLE
DRE da Rofe não apresentam vendas feitas através da nota fiscal de saída e nem as despesas lançadas.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#396]
**Descrição**
DRE Sintético
DRE Analítico p/Rubrica
DRE Analítico p/Lançamento

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
rofe

**Comment by Parapinski** [comment]
[dre-veiculo.zip](https://github.com/udisoft/roadmap/files/4325684/dre-veiculo.zip)
[dre-sintetico.zip](https://github.com/udisoft/roadmap/files/4325686/dre-sintetico.zip)
[dre-analitico-p-rubrica.zip](https://github.com/udisoft/roadmap/files/4325687/dre-analitico-p-rubrica.zip)
[dre-analitico-p-lancamento.zip](https://github.com/udisoft/roadmap/files/4325688/dre-analitico-p-lancamento.zip)
