### ISSUE TITLE
Erro de email ao recuperar a senha.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#399]
**Descrição**
Ao recuperar a senha o sistema apresenta mensagem de email não localizado, ´porém o email está correto.

**Print**
![image](https://user-images.githubusercontent.com/52629222/76962853-5b3a1c80-68f6-11ea-9203-7639698810df.png)

**Database**
marcia

**Comment by ziza** [comment]
Tem que informar é o USUÁRIO, não o e-mail
