### ISSUE TITLE
No cadastro de Produtos, na aba Fornecedores>Histórico de Fornecedores, disponibilizar coluna ID e Número da última NF

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#40]

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3397388/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3397421/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3397450/script.txt)
