### ISSUE TITLE
Ajustar contrato de compra e venda de veículos pra caber numa página

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#401]
![1](https://user-images.githubusercontent.com/49871294/77076005-f653f480-69d1-11ea-9168-86a8cd599411.jpeg)
![2](https://user-images.githubusercontent.com/49871294/77076008-f6ec8b00-69d1-11ea-96e3-2c63818483f8.jpeg)

**Comment by Parapinski** [comment]
[ContratoCompra.zip](https://github.com/udisoft/roadmap/files/4359700/ContratoCompra.zip)
[ContratoVenda.zip](https://github.com/udisoft/roadmap/files/4359706/ContratoVenda.zip)
