### ISSUE TITLE
No Pedido de Venda, criar tela apenas para pesquisa de itens - disponibilizar atalho F?

### ISSUE THREAD

**Issue by dziza** [udisoft/roadmap#41]
**Correção**
1) Disponibilizar na tela opção para informar quantidade do item selecionado
3) No grid disponibilizar coluna Marca.
4) No botão Pesquisar apresentar atalho F4.

**Comment by Parapinski** [comment]
Implementado pesquisa com o atalho F4

**Comment by osmaroliveira** [comment]
**Correção**

Disponibilizar na tela opção para informar quantidade do item selecionado
No grid disponibilizar coluna Marca.
No botão Pesquisar apresentar atalho F4.

**Comment by dziza** [comment]
1 - Na tela de seleção de item colocar os campos "Quantidade", "Preço", "Valor Total" abaixo do grid
2 - Ao selecionar um item no grid preencher "Quantidade" = 1, "Preço" = "Preço do Item" e "Valor Total" = Quantidade x Preço
3 -  Ao alterar a quantidade recalcular o valor total

**Comment by osmaroliveira** [comment]
Disponibilizar campo Código na tela de filtro, e criar lista de opções com "ID", "Código", "GETIN/EAN", e "Referencia". Pesquisar o código conforme setado na lista.

**Comment by dziza** [comment]
Demais alterações nesta tela favor abrir novas demandas

**Comment by Parapinski** [comment]
Realizado implementações solicitadas.

**Comment by osmaroliveira** [comment]
Ao clicar no botão OK para incluir o item no pedido apresenta o erro abaixo.

![image](https://user-images.githubusercontent.com/52629222/62886612-706c1e80-bd09-11e9-9b1e-aa6a6d1f83ec.png)
