### ISSUE TITLE
As despesas geradas pela importação de notas de despesas devem compor o frete fob caso a nota tenha frete rateado nos itens.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#411]
![image](https://user-images.githubusercontent.com/52629222/77687858-7dc2da00-6f75-11ea-9084-4b1ce1b1e266.png)

**Database**
Décio

**Comment by ziza** [comment]
A despesa é lançada pelo valor do custo e no custo já está somado o frete fob.
