### ISSUE TITLE
Saldo de estoque do item está diferente do saldo de estoque do lote/almoxarifado

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#413]
Favor corrigir o saldo de estoque das 2 situações a seguir

SITUAÇÃO 1: O item ID 375 está com o saldo de estoque diferente do saldo dos lotes, verifiquei que na aba RASTRO não tem o LOTE 2019 de 624 unidades, esse lote está na nota fiscal de entrada ID 1164 do dia 25/11/19. Nessa mesma nota há mais 2 lotes desse item e os mesmos estão aparecendo no rastro.SALDO TOTAL CORRETO = 771

SITUAÇÃO 2: O item ID 615 está com o saldo de estoque ATUAL=zero e na aba SALDO DE ESTOQUE, no almoxarifado central=20. SALDO TOTAL CORRETO = 0

banco: soumaissaude

![image](https://user-images.githubusercontent.com/53786319/78025978-ec62b780-7328-11ea-9654-8e8fc63f178f.png)
![image](https://user-images.githubusercontent.com/53786319/78026039-013f4b00-7329-11ea-93ca-96fed22ae967.png)
![image](https://user-images.githubusercontent.com/53786319/78026057-0a301c80-7329-11ea-8a07-88b945aba4f0.png)
![image](https://user-images.githubusercontent.com/53786319/78026081-16b47500-7329-11ea-96a5-a12f39ef96a1.png)

**Comment by Parapinski** [comment]
Saldos ajustados
