### ISSUE TITLE
Na tela de Extrato de Vale de Funcionário ao abrir a lista não aparece nenhum funcionário mesmo com lançamentos de vale efetuado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#416]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
![image](https://user-images.githubusercontent.com/52629222/78451489-eb48c780-7653-11ea-8b6e-3a81edee9207.png)

![image](https://user-images.githubusercontent.com/52629222/78451504-fd2a6a80-7653-11ea-8bd2-ad2b042959e9.png)

**Database**
demo

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4431728/script.txt)
