### ISSUE TITLE
Separar campos de data e hora na tela do pedido.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#419]
**Descrição**
Corrigir os relatórios que se utilizam desse campo.

Criar máscara no campo Data Final como os demais campos de data do Udisys
![image](https://user-images.githubusercontent.com/52629222/79043557-c1505180-7bcd-11ea-9cc5-98a78cb936c1.png)

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Recibo Online - 23122019.pdf](https://github.com/udisoft/roadmap/files/4478057/Recibo.Online.-.23122019.pdf)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4478064/script.txt)
