### ISSUE TITLE
Erro ao processar arquivo de retorno do banco sicredi.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#422]
**Print**
![image](https://user-images.githubusercontent.com/52629222/78999334-63156700-7b18-11ea-831f-5f339d8b1dda.png)

![image](https://user-images.githubusercontent.com/52629222/78999468-b1c30100-7b18-11ea-918e-dc908d0ded78.png)

Arquivo de retorno renomeado
[28194413.TXT](https://github.com/udisoft/roadmap/files/4462024/28194413.TXT)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4483716/script.txt)
