### ISSUE TITLE
Implementar calculo da composição do custo de aquisição levando em consideração o regime tributário.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#425]
**Regime Simples Nacional:**
(custo do produto na nota + valor acrescimo - valor desconto + valor despesa acessoria + valor frete + valor icms substituição + valor ipi):

**Regime Lucro Presumido:**
(custo do produto na nota + valor acrescimo - valor desconto + valor despesa acessoria + valor frete + valor icms substituição + valor ipi - valor icms normal - valor icms desonerado - valor icms frete fob):

**Regime Lucro Real:**
(custo do produto na nota + valor acrescimo - valor desconto + valor despesa acessoria + valor frete + valor icms substituição + valor ipi - valor icms normal - valor icms desonerado - valor icms frete fob - valor pis recuperar - valor cofins recuperar):

1) Verificar o regime tributário selecionado nos parâmetros da empresa.
2) Criar campo Custo de Aquisição
3) Substituir na tela de configuração por empresa o campo Ultimo Custo pelo Custo de Aquisição.
4) Na aba Fornecedores/Histórico de fornecedores substituir campo Preço Médio por Preço Aquisição.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4689785/script.txt)

**Comment by Parapinski** [comment]
[script425.txt](https://github.com/udisoft/roadmap/files/4713343/script425.txt)

**Comment by Parapinski** [comment]
[script425.txt](https://github.com/udisoft/roadmap/files/4717982/script425.txt)
