### ISSUE TITLE
Na tela de Fechamento de Caixa, no botão Demonstrativo disponibilizar a template Demonstrativo de Fechamento.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#426]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento_caixa.zip](https://github.com/udisoft/roadmap/files/4533966/demonstrativo-de-fechamento_caixa.zip)
