### ISSUE TITLE
Na tela do PDV Online criar opção para parametrizar botão Observação. Disponibilizar esse campo para ser possível aparecer na comanda.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#427]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Raphael RDDF

**Comment by Parapinski** [comment]
Implementado opção para adicionar observação a comanda. No template a observação estará disponível no campo "detalhe"
