### ISSUE TITLE
Tela de pedido de venda não esta tratando acréscimo sobre a venda quando acréscimo vem da tabela de preço.

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#430]
**Descrição**
Ao selecionar uma tabela de preço que tenha acréscimo sobre o preço de venda, o sistema esta setando sinal de - (menos) nos campos de desconto. Isso esta ocasionando erro na transmissão de nota.

**Print**
![image](https://user-images.githubusercontent.com/53625454/79785207-74792300-8311-11ea-86a3-c386e57c4ffd.png)

![image](https://user-images.githubusercontent.com/53625454/79785968-be163d80-8312-11ea-81d6-63d29f960642.png)

**Database**
onysion_demo

**Comment by osmaroliveira** [comment]
1) Criar campos de acréscimos no grid
2) Bloquear o campo Desconto ao inserir o item
3) Permitir edição do campo somente no grid

**Comment by dieiro** [comment]
Na tela de alteração (F2) ocorre o mesmo. O sistema esta informando o acrescimo no campo de desconto e não no campo de acrescimo.

![image](https://user-images.githubusercontent.com/53625454/79789156-c6bd4280-8317-11ea-91a6-a027637ac31f.png)

**Comment by osmaroliveira** [comment]
![image](https://user-images.githubusercontent.com/52629222/81119997-d92fa280-8ef9-11ea-929f-834bb3be5774.png)

**Comment by osmaroliveira** [comment]
O erro da duplicação do acréscimo ocorre quando a tabela é alterada.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4594676/script.txt)
