### ISSUE TITLE
Implementar recuperação de cadastro de cliente que estejam contratando novamente o Udisys.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#433]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Script433.txt](https://github.com/udisoft/roadmap/files/5832436/Script433.txt)

**Comment by osmaroliveira** [comment]
Após confirmar o código de verificar o sistema ficou travado em loop.

Cadastro do cliente utilizado para recadastro estava com status cancelado, o banco de dados estava com status inativo.

**Comment by osmaroliveira** [comment]
Após aplicar o script tentei novo cadastro, mas apresentou o erro da mensagem abaixo:

![image](https://user-images.githubusercontent.com/52629222/105536960-913eee80-5cc7-11eb-9436-82a36c366edc.png)

Cadastro usado para recuperar:
![image](https://user-images.githubusercontent.com/52629222/105537052-ba5f7f00-5cc7-11eb-82cc-b70bcbeb2fcd.png)
