### ISSUE TITLE
Implementar relatório de sugestão compra.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#436]
**Descrição**
Filtros: 
1) Dta Inicial e Final de vendas
2) Item Ativo
3) Categoria
4) Fornecedor
5) Item
6) Campo para informar "Dias para previsão de Estoque"

Analisar pelo período de venda a quantidade vendida, a quantidade encontrada dividir pelos dias do período selecionado para saber a média diária. Multiplicar esse valor pela quantidade informada no campo "Dias para previsão de Estoque", imprimir esse resultado na coluna Sugestão de compra.

Usar esse relatório como modelo. Incluir a coluna estoque mínimo e estoque máximo.
![image](https://user-images.githubusercontent.com/52629222/80639143-94a29380-8a2f-11ea-8dfb-826f79923fc4.png)

**Comment by Parapinski** [comment]
[relatorio-de-sugestao-de-compras.zip](https://github.com/udisoft/roadmap/files/5562474/relatorio-de-sugestao-de-compras.zip)
