### ISSUE TITLE
Na tela de faturamento de pedido o filtro por data emissão não está funcionando.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#439]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
![image](https://user-images.githubusercontent.com/52629222/80810511-00047680-8b92-11ea-9254-d0eec19e7f50.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
Testes efetuados em ambiente de desenvolvimento, filtro não demostra erro. Efetuar novo teste caso persista o erro me chame para verificar maiores detalhes.
