### ISSUE TITLE
Somente as vendas recebidas na forma do tipo dinheiro está gerando troco

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#445]
**Descrição**
O troco só esta sendo gerado para as formas de pagamento que seja do tipo dinheiro, para as demais não esta gerando.

**Print**
![image](https://user-images.githubusercontent.com/53625454/81440984-edb0ac80-913e-11ea-8821-e21061bdd91d.png)

![image](https://user-images.githubusercontent.com/53625454/81441060-15a01000-913f-11ea-897b-2810951e4f0d.png)

**Database**
onysion_demo

**Comment by osmaroliveira** [comment]
Corrigir o valor do recebimento que é enviado para a nota fiscal. No pedido está ficando um e na nota outro.

![image](https://user-images.githubusercontent.com/52629222/92152555-df268900-edf0-11ea-986e-734dfce12b8b.png)
