### ISSUE TITLE
Quando item no Emsys está informado o codigo de barras, a substituição por item de uso e consumo não funciona.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#447]
**Descrição**
Se no Emsys o item está informado o código de barras, e no nfast um fornecedor desse item está setado para substituir por uso e consumo, mesmo assim a importação considera como item normal de venda.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Rede MRA

**Comment by ziza** [comment]
Verificar se o NOP é de despesa e testar novamente

**Comment by ziza** [comment]
É necessário informar NOP de despesa manualmente ou configurar o de/para selecionando NOP de despesa para que a substituição do item de uso e consumo funcione corretamente.
