### ISSUE TITLE
Implementar cadastro de frota.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#450]
**Descrição**
1) Criar aba Frota no cadastro do cliente.
2) Cadastro deve conter campos (Placa, Descrição, Motorista e Tanque)
3) Permitir incluir, alterar e excluir.
4) Permitir transferir para outro cliente.
5) Permitir inativar placa

**Solicitante**
Posto Molas 21

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4669433/script.txt)

**Comment by osmaroliveira** [comment]
1) Criticar duplicidade de cadastro
