### ISSUE TITLE
Implementar no pedido de venda possibilidade de pesquisar cliente por placa.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#451]
**Descrição**
1) Apresentar campo de Placa na capa do pedido para facilitar a pesquisa. Ao selecionar a placa setar o cliente.
2) Se a placa digitada não for localizada perguntar se deseja cadastrar o veículo e na tela de cadastro possibilitar vincular a um cliente cadastrado.
3) Os dados de veículo selecionado devem ser setados nos campos da aba Veiculo.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
Horas previstas: 25 horas

**Comment by Parapinski** [comment]
[script451.txt](https://github.com/udisoft/roadmap/files/4755185/script451.txt)
Script Middleware
