### ISSUE TITLE
Implementar no pedido de venda parâmetro para impedir registro do mesmo item duas vezes.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#452]
**Descrição**
Criar parâmetro com 3 opções: 1) Não permitir registrar item que já esteja no pedido; 2) Registrar item somando a quantidade; 3) Registrar normalmente.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
Horas Previsto: 16 Horas
