### ISSUE TITLE
Implementar no pedido de venda parâmetro para determinar se a ordem dos itens registrados será: Ultimo registrado é o primeiro do grid, ou se o ultimo registrado é o ultimo do grid.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#456]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Posto Molas 21

**Comment by Parapinski** [comment]
[script456.txt](https://github.com/udisoft/roadmap/files/4719439/script456.txt)
