### ISSUE TITLE
Implementar preenchimento automatico ao importar xml do CT-e na tela de Conhecimento de Transporte

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#459]
**Descrição**
Ao importar xml do CT-e preencher automático, com os dados do CTe importado, a aba Documentos > Documentos > Documentos Anteriores
Essa opção é utilizada quando o tipo do serviço é subcontratação

![image](https://user-images.githubusercontent.com/53625454/82341292-3af21100-99be-11ea-9e13-2534d87ac55e.png)

**Solicitante**
O. A. TAVARES TRANSPORTE - ME
CNPJ 20746193000131

**Comment by osmaroliveira** [comment]
peguei um cte qualquer e importei na base demonstração.

![image](https://user-images.githubusercontent.com/52629222/92177755-1b68e200-ee0f-11ea-8efb-525752f61002.png)
