### ISSUE TITLE
Ao enviar boleto por email ou whatsapp para uma cobrança com mais de um título, o sistema está duplicando o nome do pagador conforme a quantia de títulos

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#46]
**Descrição**
Ajustar a descrição da mensagem melhorando assim a comunicação com o cliente.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by dziza** [comment]
Após atualização alterar no tipo de cobrança a linha:
"Prezado Cliente [titulos {pessoa.nome}]" -> "Prezado Cliente {pessoa.nome}"

**Comment by osmaroliveira** [comment]
**Correção**
Os dados da pessoa está vindo em branco.

**Comment by osmaroliveira** [comment]
A variável {pessoa.nome} não está sendo substituída no envio pelo Whatsapp.
