### ISSUE TITLE
Buscar solução para impedir que uma nota seja importada em duplicidade ao clicar aos mesmo tempo sobre o botão importar.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#461]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by ziza** [comment]
Será realizado uma tentativa de bloquear isso, porém a performance será bastante afetada.
