### ISSUE TITLE
Implementar nos dados adicionais da template de NF-e e NFS-e a impressão da placa, odometro e motorista.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#463]
**Descrição**
Quando no Pedido de Venda, na aba Veículo, os campos Placa, Odometro ou Motorista estiverem preenchidos, envia-los para os dados adicionais da NF-e e NFS-e.

Obs: Campo Motorista tem que ser implementado.

**Solicitante**
Posto Molas 21

**Comment by Parapinski** [comment]
Tempo previsto: 4-Horas

**Comment by Parapinski** [comment]
[script463.txt](https://github.com/udisoft/roadmap/files/4697498/script463.txt)
