### ISSUE TITLE
Implementar em pedido de venda, na tela de edição/alteração do item, campo para informar o técnico, separando assim o vendedor do técnico.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#465]
1) No campo Vendedor filtrar apenas os Vendedores
2) No campo Técnico Filtrar apenas os Técnicos
3) No campo Vendedor trazer setado o vendedor da capa
4) No campo técnico deixar em branco para seleção
5) Criar tabela para informar técnico por empresa como é feito com vendedor.

**Solicitante**
Interno

**Comment by Parapinski** [comment]
[Script465.txt](https://github.com/udisoft/roadmap/files/5279072/Script465.txt)

**Comment by Parapinski** [comment]
[Script465.txt](https://github.com/udisoft/roadmap/files/5282635/Script465.txt)
