### ISSUE TITLE
No De/Para da tributação tratar a origem do CST (0, 1 e 2)

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#466]
Chave NF-e para exemplo
52200528810269000152550010000286161112610632

**Solicitante**
Base Décio Macedo e Souza

**Comment by ziza** [comment]
![image](https://user-images.githubusercontent.com/49871294/83355040-3a009e00-a333-11ea-9b41-505eeddd5549.png)

Estávamos pegando apenas a tag "CST" onde vem "20", agora será concatenado com a tag "orig" pra ficar "120"

**Comment by ziza** [comment]
Será necessário reprocessar as notas que estiverem com erro.
