### ISSUE TITLE
No arquivo de retorno, quando houver registro de ocorrência de "Tarifa de Baixa da Carteira" não permitir selecionar. 

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#47]
**Descrição**
Evitar que no retorno se processe registros indevidamente já que no retorno outras informações do título não estão sendo identificadas.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by osmaroliveira** [comment]
[28194715.txt](https://github.com/udisoft/roadmap/files/3437134/28194715.txt)

**Comment by Parapinski** [comment]
Implementada remessa de baixa de títulos no banco. Caso identificar o cliente e ou motivo para o chamado, reabrir com maior detalhamento do processo que está sendo executado.

**Comment by osmaroliveira** [comment]
*Descrição*
Evitar que o registro seja selecionado e o título seja liquidado com o valor da baixa.

**Comment by dziza** [comment]
1 - Lançar a despesa desses registros caso o usuário deixe marcado
2 - Verificar reflexo na DRE [ Despesa Financeira ]

**Comment by dziza** [comment]
3 - Vincular pessoa no cadastro de bancos
4 - No tipo de cobrança criar grid pra vincular as categorias financeiras em cada tipo de despesa proveniente do retorno bancário

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3511056/script.txt)

**Comment by Parapinski** [comment]
Implementado no retorno de cobrança, lançamento de despesas provenientes de tarifa bancária.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3555890/script.txt)
