### ISSUE TITLE
Implementar otimizador de cadastros possibilitando a troca de classes fiscais.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#472]
**Descrição**
Facilitar a troca da classe fiscal quando houver uma mudança de regime tributário de Simples para Presumido por exemplo.
Permitir que esse otimizador tenha possibilidade de ser implementado com outras possibilidades de troca.

Criar filtro por: Categoria, Marca, Fornecedor, Classe Fiscal, NCM

**Solicitante**
Interno

**Comment by Parapinski** [comment]
Horas previstas: 16 Horas
