### ISSUE TITLE
Quando há informação de forma de pagamento vinculada no cliente essa forma aparece só na finalização da venda da empresa 1 do banco de dados.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#474]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
Problema não ocorreu após teste!
