### ISSUE TITLE
Sistema não está obedecendo a regra de Limite de crédito de clientes

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#478]
Ao lançar a venda para um cliente com limite "estourado" (mensal e total) o sistema está permitindo finalizar em carteira, sem pedir liberação.

* se caso o cliente estiver com limite = ZERO = entender que está ILIMITADO
* bloquear somente com limite acima de ZERO

**Comment by Parapinski** [comment]
Tempo estimado: 6 horas
