### ISSUE TITLE
Implementar envio remessa de solicitação de baixa

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#48]
**Observação**
Criar flag Baixa Solicitada, e ao baixar o título manualmente setar flag Baixa Solicitada = Sim e enviar informação à remessa.

**Descrição**
Melhorar os processos de tratamento dos boletos bancários evitando assim trabalho manual.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3423431/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3428464/script.txt)
