### ISSUE TITLE
Implementar na tela de Manutenção de Contas a Receber possibilidade de imprimir recibo do valor liquidado em Dinheiro/Cartão/Cheque a Vista/Outros a Vista

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#480]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Posto Molas 21

**Comment by Parapinski** [comment]
Previsto: 8 horas

**Comment by Parapinski** [comment]
[ReciboContasReceber.zip](https://github.com/udisoft/roadmap/files/4807885/ReciboContasReceber.zip)
