### ISSUE TITLE
Implementar na tela de Fórmula de Produtos um terceiro tipo "Produção Automatizada"

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#485]
A finalidade desse tipo seria a geração automática de ordem de produção ao vender o item acabado, ou seja, na tela de pedido de venda ou no pdv, ao vender o item Produto Acabado que contenha fórmula, a produção do item seria gerado no momento da venda.

Para os itens com tipo = 04 - Produto Acabado, ao vender se tiver estoque pega do estoque, se não tiver realizada a produção automática caso esteja com esse tipo de produção automatizada no cadastro de fórmula.

![image](https://user-images.githubusercontent.com/52629222/85611567-12e17780-b626-11ea-857c-1386987f4b14.png)

**Solicitante**
Raphael - Quero Açai

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4886708/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4891326/script.txt)

**Comment by Parapinski** [comment]
[script485.txt](https://github.com/udisoft/roadmap/files/4893407/script485.txt)
