### ISSUE TITLE
Ajustes na Baixa Parcial de Títulos a Receber

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#486]
**Descrição**
1) Na tela de recebimento só apresentar a baixa parcial anterior quando a data de movimentação for a mesma do dia e o operador que baixou for o mesmo.
2) No recibo de baixa apresentar o Saldo atual do título e o valor que se está baixando.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[ReciboContasReceber.zip](https://github.com/udisoft/roadmap/files/4860594/ReciboContasReceber.zip)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/4860621/script.txt)

**Comment by osmaroliveira** [comment]
No grid de lote da tela de Manutenção de Titulos, o campo Valor Bruto está trazendo o valor já com os juros calculados, o correto é trazer apenas o valor do título.

![image](https://user-images.githubusercontent.com/52629222/86365355-687ddb80-bc47-11ea-9346-fb8b1f663f2a.png)

**Comment by osmaroliveira** [comment]
**Após um título ser liquidado parcialmente os juros do título remanescente não bate com os juros do lote. Nessa imagem o juro de cima deve ser o mesmo de baixo para fechar os valores.**

![image](https://user-images.githubusercontent.com/52629222/86500997-277ae980-bd63-11ea-9313-40026bc05f28.png)

**Se estorno um recebimento parcial e me mantenho na tela de manutenção e solicito um nova pesquisa os valores do lote não são atualizados, para ter reflexo tenho que sair da tela e acessar novamente.**

![image](https://user-images.githubusercontent.com/52629222/86501053-88a2bd00-bd63-11ea-83ee-d88cd00cb29d.png)

**Comment by osmaroliveira** [comment]
Ao informar o juro manualmente do grid de cima o juro do lote não é atualizado.

![image](https://user-images.githubusercontent.com/52629222/86940348-b2b40080-c110-11ea-8967-c93c7dfe15e1.png)

Após liquidação realizar uma nova pesquisa automática para que os valores sejam atualizados.

![image](https://user-images.githubusercontent.com/52629222/86940679-1dfdd280-c111-11ea-8ca4-8012aab751c7.png)

Quando o valor dos juros é maior que o valor bruto e ocorre uma liquidação parcial (nesse caso eu liquidei apenas o valor dos juros)

![image](https://user-images.githubusercontent.com/52629222/86941200-ada38100-c111-11ea-959b-4c0e4f770fe4.png)

![image](https://user-images.githubusercontent.com/52629222/86941401-e5aac400-c111-11ea-89d9-52cc1ba4eace.png)

Após estornar a liquidação o valor dos juros fica negativo.

![image](https://user-images.githubusercontent.com/52629222/86941601-20acf780-c112-11ea-8a81-5f1dff8675d4.png)

**Comment by Parapinski** [comment]
[script486.txt](https://github.com/udisoft/roadmap/files/4915510/script486.txt)

**Comment by osmaroliveira** [comment]
Arredondamento do calculo dos juros.

![image](https://user-images.githubusercontent.com/52629222/87543598-04114200-c673-11ea-9442-291b5de521de.png)

**Comment by osmaroliveira** [comment]
Liquidei parcial um título onde o juro era maior que o capital, liquidei apenas o valor do juro. Acessei o sistema com outro usuário e abri a liquidação do mesmo titulo. O valor que deveria estar disponível para liquidação era de 100,00 mas aparece outro.

![image](https://user-images.githubusercontent.com/52629222/87579169-80237e00-c6a3-11ea-96b2-a763e2fae09f.png)
