### ISSUE TITLE
Implementar Painel no Dashboard de Pedido/OS que não esteja com situação = Recebido.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#489]
**Descrição**
Colunas: Emissão, Cliente, Valor Total Produtos, Valor Total Serviços, Situação. (Para cada situação implementar uma cor)

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[script489_MID.txt](https://github.com/udisoft/roadmap/files/4931965/script489_MID.txt)

**Comment by Parapinski** [comment]
[script489_MID.txt](https://github.com/udisoft/roadmap/files/4931976/script489_MID.txt)

**Comment by Parapinski** [comment]
1) Status em andamento mudar cor para verde e negritar
2) o ano da data de emissão está cortado
3) Status concluido mudar cor para roxo
4) Verificar possibilidade de totalizar Serviço, Produto e Total
5) Aumentar campo Situação pra caber Em Andamento

**Comment by osmaroliveira** [comment]
É possível disponibilizar essa linha na vertical?

![image](https://user-images.githubusercontent.com/52629222/87858368-6e3c1800-c8fb-11ea-8614-b1d5f54ecb9d.png)
