### ISSUE TITLE
Na lista de pessoas do contas a pagar possibilitar habilitar mais colunas de pesquisa.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#49]
**Correção**
Na lista de pessoas dos títulos quando setado cidade está vindo o ID e não o nome.

**Descrição**
Criar em parâmetro lista de opções assim como o pedido de venda

**Comment by osmaroliveira** [comment]
**Correção**

Na lista de pessoas dos títulos quando setado cidade está vindo o ID e não o nome.

**Comment by Parapinski** [comment]
Ajustado lista de pessoas para apresentar o nome da cidade.
