### ISSUE TITLE
Implementar classificação Contador

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#493]
**Descrição**
1) Criar aba Contador
2) Implementar campo CPF e CRC
3) Compor o XML da nota com o CNPJ
4) Compor o Sped com o CPF

** Contador está vinculado no cadastro da empresa

**Solicitante**
Raphael RDDF

**Comment by Parapinski** [comment]
[script493.txt](https://github.com/udisoft/roadmap/files/4956259/script493.txt)
