### ISSUE TITLE
Implementar cheque devolvido.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#498]
**Descrição**
1) Implementar controle de devolução
2) Implementar depósito em lote.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Script498.txt](https://github.com/udisoft/roadmap/files/5642974/Script498.txt)

**Comment by Parapinski** [comment]
[Script498.txt](https://github.com/udisoft/roadmap/files/5643010/Script498.txt)

**Comment by osmaroliveira** [comment]
**ERRO AO CONFIRMAR A BAIXA DO LOTE**
![image](https://user-images.githubusercontent.com/52629222/101203121-9b862a00-3640-11eb-9f88-b66d19384a38.png)

**Comment by Parapinski** [comment]
Gerar movimento financeiro no deposito, alterando o status do cheque para compensado.
Caso houver devolução de cheque, realizar movimento financeiro contrário no sistema, gravando a informação de devolução e a Alínea no log do cheque.

**Comment by Parapinski** [comment]
[Script498.txt](https://github.com/udisoft/roadmap/files/5777641/Script498.txt)

**Comment by osmaroliveira** [comment]
Correções:

1) Ao devolver um cheque o registro do depósito não pode ser excluído e um novo registro da devolução deve ser gerado.
2) Ao devolver permitir informar a data além do motivo e gerar o registro na data informada, porém a data informada não pode ser inferior a do depósito e nem superior a atual.

**Comment by osmaroliveira** [comment]
1) Na tela de devolução de cheque em lote retirar pesquisa por categoria e implementar pesquisa por valor.
2) Na tela de devolução de cheque em lote alterar nome da tela para "Devolução de Cheque em Lote"
![image](https://user-images.githubusercontent.com/52629222/105999327-ed1cc500-6083-11eb-95f3-3ffcfcab7589.png)

**Comment by Parapinski** [comment]
[Script498.txt](https://github.com/udisoft/roadmap/files/5880640/Script498.txt)

**Comment by osmaroliveira** [comment]
1) Formatar o campo
![image](https://user-images.githubusercontent.com/52629222/106201849-7371fd80-618f-11eb-85a4-c5d27de36988.png)

2) Corrigir mensagem. A data informada foi menor que a data do depósito.
![image](https://user-images.githubusercontent.com/52629222/106202032-baf88980-618f-11eb-9d4a-e8c83b5343ca.png)

3) Não permitir devolver cheque com data maior que a data do dia. Ou seja, a data de devolução deve ser maior que a data do depósito e menor que a data do dia.

**Comment by osmaroliveira** [comment]
Não encontrei opção para liberar direito de acesso.

![image](https://user-images.githubusercontent.com/52629222/106360168-63703000-62ed-11eb-9d52-cf8c097b700a.png)

**Comment by Parapinski** [comment]
[script498Mid.txt](https://github.com/udisoft/roadmap/files/5898908/script498Mid.txt)
