### ISSUE TITLE
Título a Receber liquidado ao mesmo tempo.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#502]
**Descrição**
Mesmo título aberto em computadores diferentes ao mesmo tempo e liquidado em contas caixa diferente.
Bloquear tanto para o título a receber quanto para o a pagar.

**Print**
![image](https://user-images.githubusercontent.com/52629222/87463337-3e310400-c5df-11ea-944c-67f877a4f128.png)

![image](https://user-images.githubusercontent.com/52629222/87463498-7df7eb80-c5df-11ea-819d-813a709f7d7d.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
[script502.txt](https://github.com/udisoft/roadmap/files/4933882/script502.txt)
