### ISSUE TITLE
Frete fora está compondo a BC ICMS e IPI não.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#503]
**Descrição**
Frete quando vem fora da nota está compondo a BC de ICMS e não deve. IPI tem que compor a BC ICMS e não está compondo.

Nota 35200715874695000108550010000129821247101462

**Print**
3º Item como exemplo. Base de Calculo 52,42
![image](https://user-images.githubusercontent.com/52629222/87553930-843ea400-c681-11ea-965b-190f618764e4.png)

No NFast está somando o frete fora e não está somando o IPI
![image](https://user-images.githubusercontent.com/52629222/87554123-bc45e700-c681-11ea-9a23-9ae7b0164d7b.png)

**Database**
Decio Variedades

**Comment by ziza** [comment]
Flga no cadastro da tributação não estava marcada
