### ISSUE TITLE
Implementar módulo Pedido de Compras

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#513]
**Descrição**
*Analisarmos como faremos.*

1) Capa: Emissão, Número, Fornecedor,  Detalhe e Situação.

2) Botão Situação para permitir a mudança (Pendente, Aprovado, Confirmado, Entrega Parcial, Entrega Total.

3) Aba Detalhe: 1) Permitir informar o tipo de pagamento (Parcelado, Cheque, Antecipado) se parcelado permitir informar os parcelamentos. 2) Campo Total Pedido. 3) Previsão de Entrega.

4) Aba Itens: 1) Permitir pesquisar item por ID, código, referencia, EAN, Descrição e Fornecedor, 2) Permitir informar quantidade, unidade de compra e custo. 3) Permitir alteração pelo grid. 4) Disponibilizar botão "Reposição" onde o operador terá a opção de informar entre datas, categoria e fornecedor. Ao pesquisar, o sistema faria a varredura trazendo para a tela os produtos com a quantidade vendida no período selecionado. 5) No grid dos itens disponibilizar as colunas ID, Código, Descrição, Unidade, Quantidade, Custo Unitário, Custo Total, Ultimo Custo e Ultimo Fornecedor, Estoque Minimo, Estoque Máximo.

5) Botão Imprimir

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Script513.txt](https://github.com/udisoft/roadmap/files/5585812/Script513.txt)

**Comment by osmaroliveira** [comment]
**No pagamento considerar o que foi informado na aba detalhe**
![image](https://user-images.githubusercontent.com/52629222/100021718-4e8c9300-2db8-11eb-9f13-c2387d105200.png)


**Na origem da movimentação criar Pedido de Compra**
![image](https://user-images.githubusercontent.com/52629222/100021961-bcd15580-2db8-11eb-93d0-e7ed35ca6fee.png)

**Criar opção para estornar**
![image](https://user-images.githubusercontent.com/52629222/100022102-face7980-2db8-11eb-8b3b-acb4936dafae.png)

**Criar parâmetro para definir se o número do pedido será o mesmo do ID caso o número não seja preenchido manualmente. Igual ao pedido de venda**
![image](https://user-images.githubusercontent.com/52629222/100022362-64e71e80-2db9-11eb-91ba-a122244cd683.png)

**Na reposição faltou o filtro por Categoria**
![image](https://user-images.githubusercontent.com/52629222/100022507-ad9ed780-2db9-11eb-9ba9-9f0f9038cdcc.png)

**Ao maximizar a tela aumentar também o grid dos produtos**
![image](https://user-images.githubusercontent.com/52629222/100022628-e6d74780-2db9-11eb-8352-487a7df5448a.png)


**Custo unitário está pegando o custo de aquisição, corrigir para o ultimo custo unitário**
![image](https://user-images.githubusercontent.com/52629222/100023025-9ca29600-2dba-11eb-87cf-34f79474891f.png)

**Custo total não está sendo multiplicado pela quantidade**
![image](https://user-images.githubusercontent.com/52629222/100023107-c2c83600-2dba-11eb-8021-8526ee9944c2.png)

**Comment by Parapinski** [comment]
Para o teste, Id da template do relatório deve ser 88.
[relatorio-pedido-de-compras.zip](https://github.com/udisoft/roadmap/files/5603282/relatorio-pedido-de-compras.zip)
