### ISSUE TITLE
Udisys não esta calculando ICMS-ST, mesmo com classe fiscal configurada.

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#515]
**Descrição**
Na tela de nota fiscal de saída, ao incluir os produtos, não esta setando a base de calculo no campo BC ICMS-ST na aba ICMS.
Sistema deve trazer o valor da base e calcular o valor do ICMS-ST conforme configurado na classe fiscal.

**Print**

![image](https://user-images.githubusercontent.com/53625454/88710677-f7fe9900-d0e4-11ea-858b-e098b6908553.png)

![image](https://user-images.githubusercontent.com/53625454/88710821-2da38200-d0e5-11ea-8625-55e97a638bc8.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by osmaroliveira** [comment]
Calculo BC ICMS-ST = Subtotal do item(240,00) + % MVA ICMS-ST(50%) = 360,00
Calculo Total ICMS-ST = BC ICMS-ST(360,00) * % ICMS-ST(17,5) = 63,00

![image](https://user-images.githubusercontent.com/52629222/89429912-22b3a780-d70c-11ea-9523-f97725cb034a.png)

**Comment by Parapinski** [comment]
[Teste Dev.zip](https://github.com/udisoft/roadmap/files/5045923/Teste.Dev.zip)
Em teste, calculo ocorreu normalmente.
