### ISSUE TITLE
Ajustes no Fechamento de Caixa

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#516]
**Descrição**
1) Implementar no usuário, no controle de caixa gerencial terceira opção "Advanced"
2) O bloqueio da conciliação quando o Fechamento de Caixa não estiver confirmado deve ser considerado apenas quando estiver setado "Advanced"

![image](https://user-images.githubusercontent.com/52629222/88943501-8f84f880-d259-11ea-8758-b1ca902d5c2a.png)

--- 3) Se estiver setado opção "Advanced" a transferência de espécie do caixa do operador para o caixa transitório deve ocorrer apenas na confirmação do caixa.

4) Se estiver setado opção "Sim" a transferência de espécie do caixa deve ocorrer com o valor informado na tela de fechamento simples. 
![image](https://user-images.githubusercontent.com/52629222/89044401-e94bf800-d317-11ea-9212-76848c20b7ce.png)

5) Impedir estorno de fechamento de caixa quando houver algum movimento do caixa conciliado.
6) possibilitar alteração troco final no fechamento
7) Se caixa operador e caixa transitório seja o mesmo não gerar troco inicial e final
8) Implementar aba Ajuste de Sobre de Caixa.
9) A tela de Fechamento de Caixa deve aparecer para o usuário mesmo quando "Movimenta Caixa Gerencial" estiver não. O acesso, alteração e exclusão dos movimentos de caixa deve obedecer o acesso do usuário.
10) Na aba Vendas filtrar apenas as vendas recebidas.
11) Na aba duplicada do cartão acrescentar coluna "Num. Transação"

**Solicitante**
Quero Açai

**Comment by Parapinski** [comment]
[script516.txt](https://github.com/udisoft/roadmap/files/5126367/script516.txt)

**Comment by osmaroliveira** [comment]
1) Quando parâmetro setado como "Advanced" não ocorre registro das vendas no caixa do operador para conciliação.

**Comment by Parapinski** [comment]
Dados estão persistindo na tela de conciliação de caixa (verificar conciliação bancária também)

**Comment by Parapinski** [comment]
[script516.txt](https://github.com/udisoft/roadmap/files/5146300/script516.txt)
