### ISSUE TITLE
Sistema lançando desconto da tabela de preço em duplicidade no pedido de vendas

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#519]
Configuramos uma tabela de preço com desconto de 10% só nos produtos e para destacar o desconto, ao lançar a o produto no pedido de venda, usando essa tabela, o sistema está trazendo o valor do item já com desconto e depois dando mais o desconto novamente, no exemplo das imagens em anexo o item que o PREÇO BASE é 4,00 ao lançar o item o sistema já tras ele com o valor de 3,60 e depois dá mais 0,40 centavos de desconto destacado, ficando no valor final de 3,20.
Obs. se mudar a configuração da tabela para ALTERAR O PREÇO UNITÁRIO, o sistema lança o desconto normalmente.

![image](https://user-images.githubusercontent.com/53786319/89291522-af853500-d628-11ea-8bee-200609c87577.png)

![image](https://user-images.githubusercontent.com/53786319/89291546-bca22400-d628-11ea-8a58-c3d0d753f1ff.png)

![image](https://user-images.githubusercontent.com/53786319/89291562-c3309b80-d628-11ea-88b8-b3a61966a44b.png)

**Comment by Parapinski** [comment]
WAR no FTP para teste
