### ISSUE TITLE
Bloquear em todos os documentos fiscais o botão Transmitir quando status for igual "Em Processamento"

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#52]
**Descrição**
Impedir do cliente transmitir novamente documento que já foi transmitido e força-lo a usar o botão Consultar

**Solicitante**
Interno

**Comment by Parapinski** [comment]
As telas estão habilitando o botão de transmissão apenas quando o status é igual a Pendente. Salvo tela de NFe que habilita quando status é Pendente ou Emitido OffLine.
