### ISSUE TITLE
Ajustes Tabela de Preço

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#521]
**Descrição**
1) Erro: 
Na tabela de preço, com a opção "Permitir Outros Descontos" setada em Não, no grid do pedido ao tentar alterar o desconto o sistema apresenta mensagem impedindo, porém o valor do desconto é alterado para zero e não permite informar qualquer outro valor. Porém, nos campos totalizadores de desconto o sistema está aceitando informar desconto.

Solução
Quando na tabela de preço opção "Permite Outros Descontos" estiver igual a Não bloquear os campos descontos no pedido de venda. 

![image](https://user-images.githubusercontent.com/52629222/89312936-dd2ca700-d645-11ea-93b4-ce6329eb13b3.png)

2) Erro:
Quando na tabela de preço, a opção "Permitir Outros Descontos" estiver setada em "Substituir Desconto", apresentar mensagem "Desconto informado irá sobrepor o desconto da tabela" também quando o desconto for alterado nos campos de totais de desconto.

![image](https://user-images.githubusercontent.com/52629222/89316816-8f666d80-d64a-11ea-94c4-68fbfab2d311.png)
![image](https://user-images.githubusercontent.com/52629222/89317622-9e015480-d64b-11ea-9b31-3f3aa3c0ccb9.png)

**Obs: As regras devem valer independente do "Tipo de Créscimo/Desconto" escolhido.**

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by osmaroliveira** [comment]
Parâmetro da tabela de preços Permite Outro Desconto setada em não. Ao selecionar o item apresentar o erro.

![image](https://user-images.githubusercontent.com/52629222/89715132-c0f47700-d971-11ea-81aa-324841597c11.png)

**Comment by osmaroliveira** [comment]
Com a tabela de preço configurada com 10% de desconto e bloqueada para outros descontos, está permitindo alterar o desconto pelo campo total do desconto.

![image](https://user-images.githubusercontent.com/52629222/89736315-8d2f5500-da36-11ea-8d50-e8828b5b70c7.png)

**Comment by Parapinski** [comment]
[Script521.txt](https://github.com/udisoft/roadmap/files/5074571/Script521.txt)
