### ISSUE TITLE
Ajustes no Fechamento de Caixa - Troco Final

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#524]
**Descrição**
1) Ao ajustar o troco final pelo Fechamento de Caixa não está tendo reflexo no registro de espécie para conciliação.
2) Movimentação de espécie dentro do fechamento de caixa como troca de forma de pagamento não está tendo reflexo no registro para conciliação.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
queroacai

**Comment by Parapinski** [comment]
[script524.txt](https://github.com/udisoft/roadmap/files/5035124/script524.txt)

**Comment by Parapinski** [comment]
1) Ajustado, 
[script524.txt](https://github.com/udisoft/roadmap/files/5035182/script524.txt)

**Comment by Parapinski** [comment]
1) Ajustado trigger.
2) O total em dinheiro é determinado pelo recebimento mais a diferença do valor recebido e o Toco Final (Valor Recebido em Dinheiro + (Valor do Troco Fim - Valor Recebido em Dinheiro)).

**Comment by osmaroliveira** [comment]
Não tiveram reflexo.

1) Ao ajustar o troco final pelo Fechamento de Caixa não está tendo reflexo no registro de espécie para conciliação.
2) Movimentação de espécie dentro do fechamento de caixa como troca de forma de pagamento não está tendo reflexo no registro para conciliação.

**Comment by Parapinski** [comment]
[script524.txt](https://github.com/udisoft/roadmap/files/5099820/script524.txt)

**Comment by osmaroliveira** [comment]
1) Após o caixa fechado os recebimentos alterados não aparecem no fechamento causando diferença.

2) No grid de duplicatas da aba cartão trazer o valor cheio do título. Está vindo o valor já descontado a taxa.

**Comment by Parapinski** [comment]
Disponibilizado WAR para homologação

**Comment by Parapinski** [comment]
[script524.txt](https://github.com/udisoft/roadmap/files/5105666/script524.txt)
