### ISSUE TITLE
Ajustar descrição da origem "Retorno Bancário"

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#537]
![image](https://user-images.githubusercontent.com/49871294/90637985-16971200-e203-11ea-86ea-4cdbea40500d.png)

**Comment by Parapinski** [comment]
[Script537.txt](https://github.com/udisoft/roadmap/files/5096608/Script537.txt)

**Comment by ziza** [comment]
![image](https://user-images.githubusercontent.com/49871294/91198895-8b6ebe00-e6d3-11ea-9565-1c4b50339a36.png)
Continua

**Comment by Parapinski** [comment]
Aplicado script no banco de dados!
