### ISSUE TITLE
Criar no cadastro do usuário opção: Permite Editar Tributação

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#548]
**Descrição**
Criar no cadastro do usuário opção: Permite Editar Tributação ICMS? Com essa opção igual a não se mesmo com a flag Editar Produto permitida a tributação não poderá ser acessada.

**Solicitante**
Décio

**Comment by ziza** [comment]
[script-548.txt](https://github.com/udisoft/roadmap/files/5911019/script-548.txt)
