### ISSUE TITLE
Implementar cadastro usuário suporte para representantes

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#551]
**Descrição**
1) Cadastro do usuário deverá ser possível vincular pessoas cadastradas na classificação vendedor
2) Ao logar no sistema deverá listar todos os clientes que estiver vinculado  no campo Vendedor Padrão
3) Na tela de seleção de clientes criar uma nova coluna Representante e informar nessa coluna o nome do representante
4) No usuário suporte listar todas as empresas porém para os clientes que estiverem representando vinculado aparecer com a cor roxo.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Uploading Script551.txt…]()

**Comment by Parapinski** [comment]
[Script551Udisoft.txt](https://github.com/udisoft/roadmap/files/5344708/Script551Udisoft.txt)

**Comment by Parapinski** [comment]
[Script551.txt](https://github.com/udisoft/roadmap/files/5348226/Script551.txt)

**Comment by Parapinski** [comment]
[Script551.txt](https://github.com/udisoft/roadmap/files/5348622/Script551.txt)

**Comment by Parapinski** [comment]
[Script551.txt](https://github.com/udisoft/roadmap/files/5351527/Script551.txt)
