### ISSUE TITLE
Implementar informar Conhecimento de Frete na nota fiscal de entrada.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#552]
**Descrição**
Implementar aba Conhecimento de Frete na nota fiscal de entrada com os campos: 
1) Data Emissão, 2) Número do CTe, 3) Transportadora, 4) Valor do Frete

a) Gerar titulo a pagar com possibilidade de informar parcelas (a soma das parcelas deve ser o mesmo do valor do frete)
b) O Valor do frete deve compor o custo das mercadorias (ratear pelo valor)

**Comment by Parapinski** [comment]
[Script552.txt](https://github.com/udisoft/roadmap/files/5228176/Script552.txt)

**Comment by osmaroliveira** [comment]
1) No titulo gerado pelo conhecimento registrar histórico.
2) Excluir o rateio do frete se retiro as informações de frete da nota
3) Compor o custo médio

**Comment by Parapinski** [comment]
[Script552.txt](https://github.com/udisoft/roadmap/files/5234608/Script552.txt)
