### ISSUE TITLE
Implementar Juros Geral de Titulos a Receber

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#567]
**Descrição**
Em Empresas>Financeiro implementar campo Juros e se é Simples ou Composto. Com esses campos preenchidos não há necessidade de informar juros no cadastro de pessoas. Porém o que for informado no cadastro de pessoa sobrepõe esse.

**Solicitante**
Molas 21

**Comment by Parapinski** [comment]
[Script567.txt](https://github.com/udisoft/roadmap/files/5248021/Script567.txt)

**Comment by Parapinski** [comment]
[Script567.txt](https://github.com/udisoft/roadmap/files/5257324/Script567.txt)

**Comment by Parapinski** [comment]
Telas alteradas:
Cadastro de Empresa,
Cadastro de Pessoa,
Titulo Receber,
Conhecimento de Transporte (cadastro de novos remetentes, cadastro de novos destinatários),
Nota Fiscal, (Importação de nota, cadastro de pessoa),
PDV, (Cadastro de novos clientes)
