### ISSUE TITLE
Campo COR no cadastro de forma de pagto

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#572]
No cadastro de forma de pagto implementar opção para selecionar a cor que será exibida no PDV (criar aba PDV)

**Comment by Parapinski** [comment]
[Script572.txt](https://github.com/udisoft/roadmap/files/5261857/Script572.txt)

**Comment by ziza** [comment]
Alterar tipo do campo para TEXT

**Comment by Parapinski** [comment]
[Script572.txt](https://github.com/udisoft/roadmap/files/5298899/Script572.txt)
