### ISSUE TITLE
Erro ao processar retorno de cobrança

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#576]
Ao processar o arquivo de retorno de cobrança, está dando erro no tamanho do NOSSO NUMERO. erro começou no dia 21/09/20, tentei processar arquivos antigos para testar e se repetiu o erro.
Bando de dados: soumaissaude

![image](https://user-images.githubusercontent.com/53786319/93931823-4c8d5180-fced-11ea-8986-17f8b3ca76c6.png)

**Comment by Parapinski** [comment]
Anexo o arquivo de retorno

**Comment by Carlinhoslima** [comment]
[3325_00939781_20200921_C240_01.zip](https://github.com/udisoft/roadmap/files/5263947/3325_00939781_20200921_C240_01.zip)
