### ISSUE TITLE
Criar tela de cadastro de OPERADORES que serão exportados para o sistema de PDV

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#577]
A senha deve ser apenas numérica, gravar no banco apenas o MD5 (Crypt.md5(senha_numerica)), status A-Ativo I-Inativo B-Bloqueado

CREATE TABLE pdv_operador(
  id SERIAL NOT NULL,
  nome TEXT NOT NULL,
  login TEXT NOT NULL,
  senha TEXT NOT NULL,
  status TEXT NOT NULL,
  PRIMARY KEY(id),
  UNIQUE(login)
);

**Comment by ziza** [comment]
A senha deve ser apenas numérica, gravar no banco apenas o MD5 (Crypt.md5(senha_numerica))

**Comment by osmaroliveira** [comment]
Erro ao cadastrar o mesmo operador com login iguais.

![image](https://user-images.githubusercontent.com/52629222/94213086-fc0c2480-fea3-11ea-8320-edce52691525.png)

**Comment by ziza** [comment]
[Script577.txt](https://github.com/udisoft/roadmap/files/5298752/Script577.txt)
