### ISSUE TITLE
Valor liquidado errado de liquidação em lote contendo titulo com baixa parcial

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#578]
Ao liquidar contas a receber em lote, contendo titulo a receber com baixa parcial, o valor liquidado de UM dos titulos qualquer desse lote fica incorreto.
Base de dados: udisoft_demo

Ex: o titulo a receber ID 600, liquidei parcialmente R$ 400,00 do valor total de R$ 500,00, ficando em aberto R$ 100,00
![image](https://user-images.githubusercontent.com/53786319/94053755-be76a100-fda8-11ea-8514-88016127cfc3.png)

Baixei o lote ID 111, com valor total em aberto de R$ 368,03.
![image](https://user-images.githubusercontent.com/53786319/94053784-c8000900-fda8-11ea-810e-7f30358b1c29.png)

O titulo ID 600 ficou liquidado corretamente, mas o titulo ID 604 ficou com valor liquidado errado 
![image](https://user-images.githubusercontent.com/53786319/94053886-e239e700-fda8-11ea-9b94-46cfaf25c363.png)

**Comment by osmaroliveira** [comment]
Corrigir campo Valor Liquidado negativo do contas a receber para evitar divergências nos relatórios.

**Comment by Parapinski** [comment]
[Script578.txt](https://github.com/udisoft/roadmap/files/5285754/Script578.txt)

**Comment by Parapinski** [comment]
[ScriptCorrigirLiquidacaoLoteTituloParcial.txt](https://github.com/udisoft/roadmap/files/5285755/ScriptCorrigirLiquidacaoLoteTituloParcial.txt)

**Comment by osmaroliveira** [comment]
Erro ao liquidar titulos em lote.
![image](https://user-images.githubusercontent.com/52629222/94964785-4c007200-04c8-11eb-9254-2cfc0689fa6f.png)

**Comment by Parapinski** [comment]
[Script578.txt](https://github.com/udisoft/roadmap/files/5320031/Script578.txt)
