### ISSUE TITLE
Na tela de Modelo de Documento criar aba Histórico e registrar log quando o número do documento for alterado.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#58]
**Correção**
Gerar log somente quando o campo Ultimo Número for alterado, está gerando a cada clique em gravar alterações. Acrescentar log quando o campo Numeração também for alterado.

**Descrição**
Identificarmos o usuário que informou/alterou a sequência numérica do documento, evitando assim reclamações indevidas por parte do usuário.

**Solicitante**
Interno

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3435854/script.txt)

**Comment by Parapinski** [comment]
Ajustada implementação!
