### ISSUE TITLE
Implementar em Classe de Comissão o calculo de comissão por valor fixo.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#583]
**Descrição**
Implementar possibilidade de escolher se o tipo de calculo será em % ou R$, tanto para a comissão geral como para a forma de pagamento.

Deixar como padrão o tipo percentual.

![image](https://user-images.githubusercontent.com/52629222/94163434-d7895b80-fe55-11ea-8ffd-933d85cda33f.png)

**Comment by Parapinski** [comment]
[script583.txt](https://github.com/udisoft/roadmap/files/5293923/script583.txt)
