### ISSUE TITLE
No cadastro de bicos remover campos de casas decimais

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#592]
![image](https://user-images.githubusercontent.com/49871294/94590190-b1e8c180-025c-11eb-9547-0c65295163bb.png)

**Comment by ziza** [comment]
Colocar campo "tanque" no mesmo lugar onde está o "encerrante" e chegar o "encerrante pra direita" ocupando o mesmo onde antes estava as casas decimais

**Comment by Parapinski** [comment]
ALTER TABLE gas_bico DROP decimal_quant;
ALTER TABLE gas_bico DROP decimal_preco;

**Comment by Parapinski** [comment]
[Script592.txt](https://github.com/udisoft/roadmap/files/5308321/Script592.txt)
