### ISSUE TITLE
Criar tela para cadastrar layout e configurar os atalhos de produtos do PDV

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#598]
![image](https://user-images.githubusercontent.com/49871294/94808254-3bb49e00-03c7-11eb-94d5-288c2ebec426.png)

**Comment by ziza** [comment]
[Script598.txt](https://github.com/udisoft/roadmap/files/5311861/Script598.txt)

**Comment by ziza** [comment]
tipo > PRO=Produto CAT=Categoria CUS=Grupo Customizado
item > ID do produto ou da categoria
nivel > A=quando tipo=PRO / S=quando tipo=CAT/CUS
sintetico > ID do atalho pai

**Comment by ziza** [comment]
[Script598.txt](https://github.com/udisoft/roadmap/files/5312022/Script598.txt)

**Comment by ziza** [comment]
[Script598.txt](https://github.com/udisoft/roadmap/files/5312063/Script598.txt)

**Comment by ziza** [comment]
Permitir selecionar imagem somente quando grupo customizado, nas demais opções deixar a imagem null pq iremos usar a imagem do cadastro do produto/categoria

**Comment by ziza** [comment]
[Script598.txt](https://github.com/udisoft/roadmap/files/5312125/Script598.txt)

**Comment by ziza** [comment]
[Script598.txt](https://github.com/udisoft/roadmap/files/5313759/Script598.txt)

**Comment by Parapinski** [comment]
[Script598.txt](https://github.com/udisoft/roadmap/files/5320916/Script598.txt)

**Comment by osmaroliveira** [comment]
Apenas no Grupo Customizado foi possível alterar imagem.

**Comment by ziza** [comment]
![image](https://user-images.githubusercontent.com/49871294/95207847-b5c99600-07be-11eb-8df8-9631932647d2.png)
Status deve ser A-Ativo I-Inativo
