### ISSUE TITLE
Implementar opção no cadastro de PDV para selecionar o layout de atalhos

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#599]
[Script599.txt](https://github.com/udisoft/roadmap/files/5312029/Script599.txt)

**Comment by osmaroliveira** [comment]
**Cadastro do layout não aparece na lista**

![image](https://user-images.githubusercontent.com/52629222/95623577-85def480-0a43-11eb-9ad1-ad181b09d61a.png)
