### ISSUE TITLE
Pesquisar histórico na tela de manutenção de contas a receber incompleto

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#610]
Ao marcar a opção PESQUISAR HISTÓRICO na tela de manutenção de contas a receber, está aparecendo somente os títulos com status=LIQUIDADO, mas precisa aparecer também os status abaixo:
-BAIXA EM LOTE, quando o lote estiver liquidado
-BAIXA PARCIAL.

**Comment by Carlinhoslima** [comment]
Corrigindo, o status que não está aparecendo é somente o BAIXA EM LOTE,

**Comment by osmaroliveira** [comment]
1) Inverter posição das colunas Origem e Status
2) Apresentar sempre o registro do lote e sua liquidação (não apresentar os títulos que compõe o lote
3) Implementar no cadastro do lote a possibilidade também de pesquisar o origem.
