### ISSUE TITLE
Apuração de comissão com erro (JAVA)

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#615]
Ao apurar a comissão dá erro, percebi que esse erro é somente em um dia do mês de outubro

-Database = meire: dá erro no dia 01/10/2020
-Database = donachica: dá erro no dia 02/10/2020

![image](https://user-images.githubusercontent.com/53786319/95262089-83895a00-07f9-11eb-8dbb-f71d0372c5f9.png)

**Comment by ziza** [comment]
#606
