### ISSUE TITLE
DUPLICIDADE DE LIQUIDAÇÃO DO CONTAS A RECEBER - MOLAS 21

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#626]
Favor excluir uma duplicidade de liquidação do CONTAS A RECEBER de ID 1259, está com registro de recebimento duplicado, tanto na tela do titulo como tbm no boletim de caixa, com a mesma data e hora
Database: molas
![image](https://user-images.githubusercontent.com/53786319/95864340-44946080-0d33-11eb-9a9a-27875900ee70.png)
![image](https://user-images.githubusercontent.com/53786319/95864400-570e9a00-0d33-11eb-9b37-26c4f1a1b96f.png)
![image](https://user-images.githubusercontent.com/53786319/95864506-786f8600-0d33-11eb-965a-3700df78f3c1.png)

**Comment by Parapinski** [comment]
Ajustada duplicidade.
