### ISSUE TITLE
Em troca/devolução do pedido de venda, quando se altera a quantidade, sistema não está rateando os descontos conforme quantidade alterada.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#64]
**Descrição**
Informe aqui detalhadamente o problema ocorrido.

**Reprodução**
Informe aqui os passos para reproduzir o problema.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
Ajustado rateio do desconto.

**Comment by osmaroliveira** [comment]
1) O desconto e o total da devolução só é calculado apenas na primeira alteração da quantidade. Se altero a quantidade mais de uma vez não há reflex no desconto e nem no total.
2) Se excluo os itens da tela e pesquiso novamente o pedido para troca/devolução o sistema informa que esse pedido não tem item disponível para troca, o operador tem que sair da tela de pedido e entrar novamente para pesquisar.

**Comment by dziza** [comment]
O item 2 não tem nada haver com o que foi implementado nesta solicitação, este problema será verificado via #91

**Comment by dziza** [comment]
@Parapinski verificar somente o item 1, o item 2 trata-se de uma implementação bem mais demorada #91

**Comment by Parapinski** [comment]
Ajustado item 1.
