### ISSUE TITLE
Corrigir tratamento da data da baixa na tela de Manutenção de Contas a Receber

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#640]
**Descrição**
1) na tela de manutenção de contas a receber considerar a data da baixa que foi informada no grid de lote.

  a) se o sistema não estiver com o controle de caixa gerencial ativo(Não) considerar a data informada.
    a.1) validar se nos direitos do usuário está permitido a movimentação financeira com data retroativa. (implementar recurso)

  b) se o sistema estiver com o controle de caixa gerencial(Sim/Advanced) ativo bloquear a edição do campo data de baixa.

**Solicitante**
Interno

**Comment by Parapinski** [comment]
[script640Middleware.txt](https://github.com/udisoft/roadmap/files/5409111/script640Middleware.txt)

**Comment by Parapinski** [comment]
Após a execução do script, vincular o acesso aos produtos que queira a validação.
