### ISSUE TITLE
Na nota fiscal de entrada, nos detalhes do item, implementar campo Vlr Total

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#652]
**Descrição**
o Campo VLR TOTAL do item servirá para a composição do campo Total da Nota tanto para notas de entrada de emissão de terceiros como emissão própria.

Vlr do Item + ipi + st + frete + desp acessoria + seguro + acréscimo + outros - desconto

![image](https://user-images.githubusercontent.com/52629222/96724069-6ae27d80-137d-11eb-9814-de3b1a2e13ed.png)

**Para melhor visualização da descrição do produto caso o cliente selecione mais de um campo de pesquisa, aumentar o campo descrição**
![96277772-b4f4e900-0fa2-11eb-8350-d15f79788099](https://user-images.githubusercontent.com/52629222/96730704-78e7cc80-1384-11eb-8b1f-8d8f92cdafeb.png)

[43180305041647000185550010000510341418949010-procNFe (1).zip](https://github.com/udisoft/roadmap/files/5415830/43180305041647000185550010000510341418949010-procNFe.1.zip)

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Script652.txt](https://github.com/udisoft/roadmap/files/5423150/Script652.txt)
