### ISSUE TITLE
Implementar Relatório de Lotes a Vencer

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#653]
**Descrição**

[Relatorio a vencer.pdf](https://github.com/udisoft/roadmap/files/5416459/Relatorio.a.vencer.pdf)

**Solicitante**
Sou Mais Saude

**Comment by Parapinski** [comment]
[Relatorio-de-Lista-de-produtos-a-Vencer.zip](https://github.com/udisoft/roadmap/files/5459296/Relatorio-de-Lista-de-produtos-a-Vencer.zip)

**Comment by Parapinski** [comment]
Filtros: 
data_ini DATE
data_fim DATE
deposito INTEGER
