### ISSUE TITLE
Implementar relatório de comissão por venda conforme modelo.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#654]
**Descrição**
Filtro: Data Finalização Inicial e Final, Vendedor, Executor 

[RELATORIO COMISSÃO.pdf](https://github.com/udisoft/roadmap/files/5425370/RELATORIO.COMISSAO.pdf)

**Solicitante**
Canopus Moto

**Comment by Parapinski** [comment]
Parametros: 
data_ini Date, 
data_fim Date, 
vendedor Integer default 0, 
id_apuracao Integer default 0

**Comment by Parapinski** [comment]
[relatorio-de-comissao-p-venda-produto.zip](https://github.com/udisoft/roadmap/files/5433855/relatorio-de-comissao-p-venda-produto.zip)

**Comment by Parapinski** [comment]
[Script654.txt](https://github.com/udisoft/roadmap/files/5433857/Script654.txt)
