### ISSUE TITLE
Na tela de pedido de venda implementar parâmetro se se controla itens excluídos.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#665]
**Descrição**
1) Na tela de pedido de venda implementar parâmetro se se controla itens excluídos.
2) Criar aba itens excluidos e enviar para essa aba todos os itens excluidos do pedido.
3) Criar colunas Código, Descrição, Unidade, Quantidade, Valor Unitário, Desconto, Acréscimo, Vlr Total, Data, Hora e Usuário que excluíu.
4) Apresentar aba somente se houver itens excluídos.

**Solicitante**
Canopus Honda

**Comment by Parapinski** [comment]
[Script665.txt](https://github.com/udisoft/roadmap/files/5495119/Script665.txt)
