### ISSUE TITLE
Implementar no cadastro do Produto, na aba Complemento, opção "Executor na Venda?" "Sim/Não"

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#666]
**Descrição**
Essa opção servirá para, no pedido de venda, ao incluir o produto o sistema abra uma tela solicitando o executor.

**Solicitante**
Canopus Moto

**Comment by Parapinski** [comment]
[Script666.txt](https://github.com/udisoft/roadmap/files/5461681/Script666.txt)
