### ISSUE TITLE
Implementar nos parâmetros do pedido de venda parâmetro para obrigatoriedade do executor.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#667]
**Descrição**
Se parâmetro estiver como executor obrigatório, ao incluir um produto com executor na venda, abrir a tela para selecionar o executor e obrigar. Caso o parâmetro esteja não obrigatório, abrir a tela do executor mas não obrigar.

**Solicitante**
Canopus Honda

**Comment by osmaroliveira** [comment]
#666

**Comment by Parapinski** [comment]
[Script667.txt](https://github.com/udisoft/roadmap/files/5461662/Script667.txt)

**Comment by osmaroliveira** [comment]
**Mensagem apresenta mesmo se no produto não estando como obrigatório**
![image](https://user-images.githubusercontent.com/52629222/97709997-8e9a7780-1a91-11eb-898d-876e1d77940c.png)

**A tela de Executor e Complemento não deve ser apresentadas ao mesmo tempo. Primeiro Complemento e após Executor**

**No cadastro do produto remover o box Obrigatoriedade do Executor, e acrescentar no box Executor Venda a opção Bloqueia**
![image](https://user-images.githubusercontent.com/52629222/97710765-8e4eac00-1a92-11eb-949f-1bbbfa4964c3.png)
