### ISSUE TITLE
Na apuração de comissão separar comissão vendedor e executor

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#671]
**Descrição**
1) Apurar comissão separada de vendedor e executor
2) Criar 3 abas: a) Resumo *onde trará as comissões somadas; b) Vendedor *somente comissões de vendedor; c) Executor *somente comissões de executor.
3) Nos relatórios permitir filtro por Vendedor/Executor ou Todos

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Script671.txt](https://github.com/udisoft/roadmap/files/5503939/Script671.txt)

**Comment by osmaroliveira** [comment]
![image](https://user-images.githubusercontent.com/52629222/98441989-5968d780-20d8-11eb-9b50-b63becee2c63.png)

**Comment by Parapinski** [comment]
[Script671.txt](https://github.com/udisoft/roadmap/files/5504766/Script671.txt)
