### ISSUE TITLE
Juros sendo calculado errado em contas a receber quando o mesmo tem baixa parcial.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#678]
**Descrição**
Os juros calculados em contas a receber está usando como base para calculo dos juros o valor total do título. O correto é usar o valor total - pagto parcial. O que deve ser considerado sempre é a data de vencimento.

![image](https://user-images.githubusercontent.com/52629222/98696362-131aaf00-234a-11eb-8b69-6e0eb63ed72c.png)

Analisando o registro dessa baixa pelo banco de dados percebi que os juros registrado para esse título é os juros calculado até o dia da liquidação parcial. Nesse caso ao tirar um relatório de contas a receber o valor dos juros desse saldo remanescente aparece errado considerando que o juros setado é do pagto parcial e não do saldo atual.

![image](https://user-images.githubusercontent.com/52629222/98696701-7e648100-234a-11eb-8441-896ee36e59a4.png)

**Database**
ribeiro

**Comment by Parapinski** [comment]
[Script678.txt](https://github.com/udisoft/roadmap/files/5537158/Script678.txt)

**Comment by osmaroliveira** [comment]
**Em Manutenção de Contas de Receber, no grid de histórico de liquidação, apresentar mesma coluna dos juros de atualização da liquidação do título**
![image](https://user-images.githubusercontent.com/52629222/99131005-56924900-25e8-11eb-8dbf-6ae09e41b83b.png)

**Alterar nome Juros para Juros de Atualização**

**Comment by osmaroliveira** [comment]
**Ao liquidar pela tela de manutenção o udisys está considerando o valor total e não o Em Aberto**
![image](https://user-images.githubusercontent.com/52629222/99131447-8b52d000-25e9-11eb-88c1-2ba290c3bc51.png)

**No grid de lote alterar nome da coluna Valor Total para Em Aberto**

**Comment by osmaroliveira** [comment]
**O Juros não está sendo calculado ao informar uma data futura na coluna Data Juros**
![image](https://user-images.githubusercontent.com/52629222/99131713-3e232e00-25ea-11eb-86f7-b11d6ad44db5.png)

**Comment by osmaroliveira** [comment]
**Estou estornando os registros pela tela de contas a receber mas os registros permanecem conforme se vc na imagem, mesmo salvando os estornos ao liquidar novamente os registros antigos aparecem**

![image](https://user-images.githubusercontent.com/52629222/99149221-17eda480-2663-11eb-9f73-b4d8ccb40491.png)
