### ISSUE TITLE
Item que OBRIGA executor sendo lançado com executor em branco no pedido de venda

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#684]
Na tela de pedido de venda, ao lançar um item que obrigue o executor na venda, o item é lançado e abre a tela obrigando o executor, mas se o usuário sair do sistema ou até atualizar a tela (Ctrl + F5) sem preencher o campo, esse item fica salvo com o executor em BRANCO.
Obs: tela de pedido de venda configurada para GRAVAR AUTOMATICAMENTE AO INCLUIR/ALTERAR/EXCLUIR ITEM

Database = ribeiro

![image](https://user-images.githubusercontent.com/53786319/100101806-1bd6af00-2e39-11eb-8cfb-02bf76cc67f9.png)
![image](https://user-images.githubusercontent.com/53786319/100101888-36a92380-2e39-11eb-8eb6-9bd07abafd65.png)
![image](https://user-images.githubusercontent.com/53786319/100101962-50e30180-2e39-11eb-9ace-745949cce0be.png)

**Comment by osmaroliveira** [comment]
**Implementar para que ao solicitar o executor e o operador clicar em Fechar o sistema retorne para o campo de pesquisa sem incluir o item.**
**Após incluir o item apresenta erro de java**

![image](https://user-images.githubusercontent.com/52629222/100476580-569c4980-30bc-11eb-911d-b901ef919d4a.png)

**Comment by osmaroliveira** [comment]
**Na tela de seleção do executor ao clicar sobre o botao Fechar a tela tem que fechar e o cursor retornar para o campo de consulta de item sem incluir o registro. **

**Comment by osmaroliveira** [comment]
**Ao incluir o item pela tela avançado o udisys não apresenta a tela para informar o executor e já apresenta a mensagem da imagem.**
![image](https://user-images.githubusercontent.com/52629222/100520680-6a57b680-3175-11eb-8bc7-9c8f77372d94.png)
