### ISSUE TITLE
Quando a informação de peso estiver informado no cadastro do produto tratar para que a informação de volume seja preenchido tanto no pedido de venda quanto na nota.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#693]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
Se um item no pedido tiver peso informado então o registro do volume deve ser gerado, e ao receber o pedido solicitar o término do preenchimento do volume. Não permitir a emissão da nota sem as informações de volume caso o produto possua peso informado (NF-e).
