### ISSUE TITLE
DEMONSTRATIVO DE FECHAMENTO DE CAIXA contendo Contas a Receber com BAIXA PARCIAL, dando diferença nos valores

### ISSUE THREAD

**Issue by Carlinhoslima** [udisoft/roadmap#697]
No Demonstrativo de fechamento de caixa, contém títulos liquidado com mais de uma data de liquidação por título (baixa parcial), o relatório nessas datas de liquidação fica com divergência entre o TOTAL DE TITULO RECEBIDO e o VALOR DE RECEBIMENTOS

Database teste: udisoft_demo

![image](https://user-images.githubusercontent.com/53786319/101495244-b9080c00-393e-11eb-9799-45bde7220b30.png)
![image](https://user-images.githubusercontent.com/53786319/101495355-ddfc7f00-393e-11eb-994d-6052babc122f.png)
![image](https://user-images.githubusercontent.com/53786319/101495505-02f0f200-393f-11eb-9d04-2155d864cb2b.png)

**Comment by Carlinhoslima** [comment]
Demonstrativo Fechamento com diferença no total de TITULOS RECEBIDOS, quando há 2 ou mais recebimento parcial no mesmo dia.

![image](https://user-images.githubusercontent.com/53786319/105414274-a6574700-5c0d-11eb-8c0e-68c84354b45e.png)
![image](https://user-images.githubusercontent.com/53786319/105414364-c1c25200-5c0d-11eb-849b-7a10c4f1750c.png)

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento.zip](https://github.com/udisoft/roadmap/files/5858059/demonstrativo-de-fechamento.zip)
