### ISSUE TITLE
Transmissão de NFS-e Uberlândia com erro

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#699]
**Descrição**

Ao transmitir a nota de serviço esta ocorrendo erro do código de atividade. É a primeira nota de serviço emitida no município de Uberlândia.

![image](https://user-images.githubusercontent.com/53625454/102693408-c18afd00-41f0-11eb-8f4f-451b3519d40c.png)

![image](https://user-images.githubusercontent.com/53625454/102693415-c9e33800-41f0-11eb-9e0b-857cdcca9073.png)

**Solicitante**
RDDF

**Comment by Parapinski** [comment]
Preencher CNAE com a seguinte informação: 6209-1/00

**Comment by Parapinski** [comment]
Ajustado!
