### ISSUE TITLE
IPI e Despesa Acessória não estão somando no total da nota

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#702]
Base "decio", segundo o Caio contador o valor total correto seria 15205,59 (8332,45 + IPI 5869,73 + DA 1003,41)

![WhatsApp Image 2021-01-08 at 13 11 53](https://user-images.githubusercontent.com/49871294/104037347-5d39d880-51b3-11eb-8c26-3ff84564fcad.jpeg)

**Comment by ziza** [comment]
Ver com o tio que que ele acha dessa regra, eu mesmo não sei

**Comment by osmaroliveira** [comment]
IPI não está sendo calculado.

![image](https://user-images.githubusercontent.com/52629222/105631762-76cf5700-5e26-11eb-9b11-647f412d2a35.png)
![image](https://user-images.githubusercontent.com/52629222/105631780-8f3f7180-5e26-11eb-9d39-1504c9b23f1a.png)
![image](https://user-images.githubusercontent.com/52629222/105631798-a41c0500-5e26-11eb-9f6c-104cdde36f79.png)

**Comment by osmaroliveira** [comment]
Total do Item só está somando após incluir o registro.

![image](https://user-images.githubusercontent.com/52629222/105773082-a0c56e00-5f39-11eb-99f8-eda46e4f8536.png)
