### ISSUE TITLE
Despesa Recorrente

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#705]
Criar tela para cadastro de despesa recorrente
1 - Valor
2 - Dia de Competência (dia em que o job será executa pra gerar as despesas)
3 - Número de Meses
4 - Mês/Ano inicial
5 - Pessoa
6 - Categoria
7 - Grid com centros de custo e % para rateio
8 - Status da Despesa (Pendente ou Baixado, se escolher baixado tem que escolhe tb a forma de baixa)
9 - Criar JOB no servidor pra varrer esse cadastro de despesa recorrente e gerar as despesas

**Comment by Parapinski** [comment]
[Script705.txt](https://github.com/udisoft/roadmap/files/5914763/Script705.txt)
[Script705Job.txt](https://github.com/udisoft/roadmap/files/5914764/Script705Job.txt)

**Comment by Parapinski** [comment]
[Script705.txt](https://github.com/udisoft/roadmap/files/5926267/Script705.txt)

**Comment by Parapinski** [comment]
[Script705Job.txt](https://github.com/udisoft/roadmap/files/5926268/Script705Job.txt)

**Comment by Parapinski** [comment]
[Script705Job.txt](https://github.com/udisoft/roadmap/files/5927289/Script705Job.txt)

**Comment by Parapinski** [comment]
[Script705.txt](https://github.com/udisoft/roadmap/files/5928239/Script705.txt)

**Comment by Parapinski** [comment]
[Script705.txt](https://github.com/udisoft/roadmap/files/5928269/Script705.txt)

**Comment by Parapinski** [comment]
[Script705.txt](https://github.com/udisoft/roadmap/files/5928624/Script705.txt)
