### ISSUE TITLE
Receita Recorrente

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#706]
Criar tela para cadastro de receita recorrente
1 - Valor
2 - Dia de Competência (dia em que o job será executa pra gerar as receitas)
3 - Número de Meses
4 - Mês/Ano inicial
5 - Pessoa
6 - Categoria
7 - Grid com centros de custo e % para rateio
8 - Status da Receita (Pendente ou Baixado, se escolher baixado tem que escolhe tb a forma de baixa)
9 - Criar JOB no servidor pra varrer esse cadastro de receita recorrente e gerar as receitas

**Comment by Parapinski** [comment]
[Script706.txt](https://github.com/udisoft/roadmap/files/5927280/Script706.txt)

**Comment by Parapinski** [comment]
[Script706Job.txt](https://github.com/udisoft/roadmap/files/5927281/Script706Job.txt)

**Comment by Parapinski** [comment]
[Script706.txt](https://github.com/udisoft/roadmap/files/5928270/Script706.txt)

**Comment by Parapinski** [comment]
[Script706.txt](https://github.com/udisoft/roadmap/files/5928626/Script706.txt)
