### ISSUE TITLE
Relatório Evolução de Despesas

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#710]
Criar um relatório onde traga todas as despesas por "tipo de despesa" totalizado mes a mes e no final com a média, e no final uma linha comparando com o ano anterior. Segue layout abaixo.

![WhatsApp Image 2021-01-15 at 08 08 28](https://user-images.githubusercontent.com/49871294/104758534-5aa02b80-573d-11eb-83b2-d87e95e7049d.jpeg)

**Comment by Parapinski** [comment]
[Script710.txt](https://github.com/udisoft/roadmap/files/5832427/Script710.txt)

**Comment by Parapinski** [comment]
[Evolucao_de_Despesas.zip](https://github.com/udisoft/roadmap/files/5832445/Evolucao_de_Despesas.zip)

**Comment by osmaroliveira** [comment]
Valor total das despesas não bate com os valores da DRE.

**Comment by Parapinski** [comment]
[Evolucao_de_Despesas.zip](https://github.com/udisoft/roadmap/files/5850793/Evolucao_de_Despesas.zip)
