### ISSUE TITLE
Relatório Evolução de Receitas

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#711]
Mesma lógica do Relatório Evolução de Despesas

**Comment by Parapinski** [comment]
Aplicar procedure da #710

**Comment by Parapinski** [comment]
[Evolucao_de_Receitas.zip](https://github.com/udisoft/roadmap/files/5836231/Evolucao_de_Receitas.zip)

**Comment by osmaroliveira** [comment]
As receitas financeiras de Juros de títulos a receber não estão compondo o resumo de Receitas Financeiras.


![image](https://user-images.githubusercontent.com/52629222/105404119-fb8c5c00-5bff-11eb-9849-aec02d62af2f.png)

![image](https://user-images.githubusercontent.com/52629222/105403941-c41daf80-5bff-11eb-9cf8-af0f697b6960.png)

**Comment by Parapinski** [comment]
[Evolucao_de_Receitas.zip](https://github.com/udisoft/roadmap/files/5857303/Evolucao_de_Receitas.zip)

**Comment by osmaroliveira** [comment]
1) A somatória do resumo das receitas não bate com o total das receitas
2) O calculo da variação está dando sempre 100%

![image](https://user-images.githubusercontent.com/52629222/105541083-9ef77280-5ccd-11eb-97cc-416d5c818a50.png)

**Comment by Parapinski** [comment]
[Evolucao_de_Receitas.zip](https://github.com/udisoft/roadmap/files/5858587/Evolucao_de_Receitas.zip)
