### ISSUE TITLE
Desbloqueio em Confiança

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#712]
1 - Quando o cliente bloqueado tentar acessar o sistema exibir os títulos vencidos com opção de emitir o boleto
2 - Opção para o cliente anexar o comprovante de pagamento (na tabela do titulo mesmo) e liberar o sistema para uso por 3 dias, tempo suficiente pro boleto compensar, criar campos no titulo pra indicar que tem desbloqueio em confiança
3 - Criar painel no dashboard pra exibir os desbloqueios em confiança, ao dar duplo clique exibir a tela do titulo
4 - Na tela do titulo criar aba para exibir a imagem do comprovante
5 - Ao logar verificar se o cliente tem desbloqueio em confiança e deixar ele acessar caso esteja dentro dos 3 dias
6 - Cliente só pode usar desbloqueio em confiança 1x dentro do mesmo mês

**Comment by Parapinski** [comment]
[script712.txt](https://github.com/udisoft/roadmap/files/5845342/script712.txt)

**Comment by osmaroliveira** [comment]
Após enviar o comprovante, ao entrar novamente no sistema a tela de Desbloqueio de confiança está abrindo sem registro.

Reservar metade da tela para disponibilizar a mensagem abaixo para o cliente na cor azul.

"O acesso ao sistema está bloqueado por pendencia financeira. Efetue a baixa do boleto e faça o pagamento. Caso não consiga pagar o boleto faça um PIX para o código 08733238000138. Gere uma imagem do comprovante de pagamento e no botão Anexar Comprovante envie o comprovante. Após enviar o comprovante o sistema será liberado automaticamente por 3 dias para compensação da liquidação."

**Comment by Parapinski** [comment]
[script712.txt](https://github.com/udisoft/roadmap/files/5881583/script712.txt)

**Comment by Parapinski** [comment]
[script712.txt](https://github.com/udisoft/roadmap/files/5894956/script712.txt)
[script712Mid.txt](https://github.com/udisoft/roadmap/files/5894957/script712Mid.txt)
