### ISSUE TITLE
No cadastro de Pessoas, gravar o CEP em formato texto para atender necessidade de cep com zero a esquerda

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#72]
**Descrição**
Quando CEP contem zero a esquerda o sistema está retirando e ao emitir doc fiscais e boletos dá erro.

**Solicitante**
Interno

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3526767/script.txt)
