### ISSUE TITLE
Erro ao editar a nota.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#721]
**Descrição**
Após atualização, ao editar a nota dá o erro da mensagem.

**Print**
![image](https://user-images.githubusercontent.com/52629222/106655989-75153a00-6570-11eb-9b11-592b05d837dd.png)

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by ziza** [comment]
Atualizar API
