### ISSUE TITLE
Vendas geradas pela tela de Emissão e Faturamento em Lote não está gravando a data e hora.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#722]
**Descrição**
Informe aqui os passos para reproduzir o problema.

**Print**
![image](https://user-images.githubusercontent.com/52629222/106664008-e35efa00-657a-11eb-8d44-2d4f98aaf0fb.png)

**Database**
Udisoft

**Comment by Parapinski** [comment]
[Script722.txt](https://github.com/udisoft/roadmap/files/5921885/Script722.txt)

**Comment by osmaroliveira** [comment]
A hora da finalização deve obedecer também a hora local.
![image](https://user-images.githubusercontent.com/52629222/107123224-c07e5f80-6872-11eb-9239-883cbb44db5e.png)

**Comment by Parapinski** [comment]
[Script722.txt](https://github.com/udisoft/roadmap/files/5937237/Script722.txt)
