### ISSUE TITLE
Ao gerar despesa ou receita recorrente com status de baixada, utilizar o mesmo detalhe no registro da conciliação bancária e de caixa.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#728]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by Parapinski** [comment]
[Script728.txt](https://github.com/udisoft/roadmap/files/5944536/Script728.txt)
