### ISSUE TITLE
Implementar opção para habilitar e desabilitar usuário por empresa.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#730]
**Descrição**
Informe aqui detalhadamente do que se trata essa implementação e quais os reflexos no sistema.

**Solicitante**
Informe aqui qual o cliente realizou a solicitação.

**Comment by ziza** [comment]
Ja existe 
![image](https://user-images.githubusercontent.com/49871294/107274457-2fa0b300-6a2f-11eb-8521-76fe028a23f5.png)
