### ISSUE TITLE
Implementação limites de desconto cadastro pdv offline gestão

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#738]
1 - No cadastro do operador criar campo para limite de desconto
2 - No cadastro do pdv em parâmetros criar campo limitando desconto para o pdv
3 - O desconto do pdv deve sobrepor ao do operador.

![image](https://user-images.githubusercontent.com/52629222/107301155-4821c500-6a51-11eb-9ae9-2aa0d1447e43.png)

**Comment by Parapinski** [comment]
[Script738PDV.txt](https://github.com/udisoft/roadmap/files/5960371/Script738PDV.txt)
[Script738ERP.txt](https://github.com/udisoft/roadmap/files/5960372/Script738ERP.txt)
