### ISSUE TITLE
Implementar flag nas formas de pagamento se Permite Troco = SIM ou NÃO

### ISSUE THREAD

**Issue by dziza** [udisoft/roadmap#74]

**Comment by udisoft** [comment]
Na tela de checkout (recebimento/pagamento) bloquear troco quando essa opção estiver = Não

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3472222/script.txt)

**Comment by Parapinski** [comment]
Implementado campo troco. Alterada validação da tela de checkout para validar o novo campo.

**Comment by osmaroliveira** [comment]
Mesmo setando Sim o sistema não está permitindo troco.
