### ISSUE TITLE
Criar opção para ser permitido no parcelamento arredondar os valores das parcelas e lançar os centavos somente na ultima parcela.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#77]
**Descrição**
Para lojas que vendem parcelado e em carteira há dificuldade com o troco quando as parcelas saem com centavos. Com essa implementação somente a ultima parcela teria centavos.

**Solicitante**
Minozo Magazine.

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3522424/script.txt)
