### ISSUE TITLE
Gravar Log na tela de Ambiente/Contingência.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#83]
**Descrição**
Para sabermos qual usuário colocou o sistema em contingência.

**Solicitante**
Interno.

**Comment by Parapinski** [comment]
Implementado Log para a tela de Ambiente/Contingência

**Comment by osmaroliveira** [comment]
Ao clicar em salvar está apresentando a mensagem abaixo e Histórico não está sendo registrado.

![image](https://user-images.githubusercontent.com/52629222/63094634-fae59580-bf36-11e9-93fe-316c2afc92b1.png)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3511124/script.txt)
