### ISSUE TITLE
Novo servidor - Criar usuários p/ acesso nas bases

### ISSUE THREAD

**Issue by dziza** [udisoft/roadmap#87]

**Comment by osmaroliveira** [comment]
Erro ao acessar o servidor.

![image](https://user-images.githubusercontent.com/52629222/64078437-aa956400-cca8-11e9-92c7-e5c80f96af90.png)

**Comment by dziza** [comment]
o IP mudou, tem que ser IP fixo ou então me passar o novo IP para liberação no firewall
