### ISSUE TITLE
Demonstrativo de Fechamento

### ISSUE THREAD

**Issue by dieiro** [udisoft/roadmap#90]
**Descrição**
Os lotes de conta a receber não estão aparecendo no demonstrativo de fechamento.
Obs. considerar tipo de conta caixa ou banco.

**Print**
![demonstrativo](https://user-images.githubusercontent.com/53625454/62870993-992fec00-bce8-11e9-977e-704b054d56db.jpg)
![Lote](https://user-images.githubusercontent.com/53625454/62870994-992fec00-bce8-11e9-99fc-506868c40531.jpg)

**Database**
Banco: esquina
Id dos lotes gerados: 40, 41

**Comment by dziza** [comment]
@Parapinski base no FTP

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3602586/script.txt)

**Comment by dieiro** [comment]
Demonstrativo de Fechamento
1.Somar o valor dos títulos recebidos em lote nas colunas Saída(Títulos Recebidos) e Recebimento(Títulos Recebidos) no cabeçalho do demonstrativo
2.No detalhes dos títulos a coluna Valor Baixa considerar valor do campo Total Liquido da tela de Lote(atualmente esta considerando da baixa)

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento.zip](https://github.com/udisoft/roadmap/files/3616563/demonstrativo-de-fechamento.zip)

**Comment by dziza** [comment]
O item 2 não procede, o valor da baixa no relatório está batendo com o valor da baixa no lote

**Comment by Parapinski** [comment]
[demonstrativo-de-fechamento.zip](https://github.com/udisoft/roadmap/files/3616708/demonstrativo-de-fechamento.zip)
