### ISSUE TITLE
Permitir devolução do restante de um item parcialmente devolvido

### ISSUE THREAD

**Issue by ziza** [udisoft/roadmap#91]
No pedido de venda se excluo os itens da tela e pesquiso novamente o pedido para troca/devolução o sistema informa que esse pedido não tem item disponível para troca, o operador tem que sair da tela de pedido e entrar novamente para pesquisar.

**Comment by osmaroliveira** [comment]
A exclusão é referente aos itens da aba Troca/Devolução.

**Comment by osmaroliveira** [comment]
1) Na segunda devolução os valores estão vindo zerados conforme a imagem.
2) Na tela de troca/devolução ao buscar pedido filtrar apenas os pedidos que tenham itens a serem devolvidos/trocados.


![image](https://user-images.githubusercontent.com/52629222/71766614-282be380-2ed8-11ea-8756-217147fb364c.png)
