### ISSUE TITLE
Em Pedido de Venda a Tela de alteração de Itens está permitindo descontos negativos.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#93]
**Descrição**
Abre a tela de alteração de item e informe um desconto com valor negativo.

**Print**
Sempre que possível anexe imagens da tela onde o problema ocorreu.

**Database**
Informe aqui o nome do banco de dados onde o problema ocorreu.

**Comment by Parapinski** [comment]
Não permitido valores negativos para desconto.
