### ISSUE TITLE
Separar o recurso "Editar Preço Unitário" para itens tipo Produto e Serviço.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#94]
**Descrição**
Possibilitar que a edição de preço em Pedido de Venda possa ser definido por produto ou serviço. Geralmente a edição de valores é necessário para itens de serviço enquanto que produtos não.

**Solicitante**
Cometa Motos

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3517258/script.txt)

**Comment by Parapinski** [comment]
[script_middleware.txt](https://github.com/udisoft/roadmap/files/3517274/script_middleware.txt)
