### ISSUE TITLE
Impedir o estorno de Pedido quando a nota fiscal vinculada estiver com status Em Processamento, Autorizada e Emitido Offline.

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#96]
**Descrição**
Caso a nota esteja em processamento e o cliente estorne a venda essa nota irá faltar no sistema causando problema na contabilidade pois o xml da mesma não será enviado.

**Solicitante**
Interno

**Comment by osmaroliveira** [comment]
- Criar mensagem "Nota Fiscal vinculada Em Processamento, favor consultar status."

**Comment by osmaroliveira** [comment]
Bloqueio só ocorrer se eu sair da tela de Pedido e acessar novamente. Se o operador estiver dentro do pedido e ao emitir a nota ela ficar com status em processamento é possível estornar.

**Comment by osmaroliveira** [comment]
Só permitir estorno do pedido quando o status do documento fiscal estiver como Pendente.

Simulação:
Fiz um pedido e gerei nota, fui alterando os status da nota e estornando os pedidos. Somente no status Em Processamento o estorno foi bloqueado, em todos os demais consegui estornar.

**Comment by dziza** [comment]
Permitir estorno quando NF cancelada OU pendente
