### ISSUE TITLE
Implementar módulo de Controle de Licitação/Empenho

### ISSUE THREAD

**Issue by osmaroliveira** [udisoft/roadmap#98]
**Descrição**
- Em pessoas implementar classificação Órgão Público
- Implementar tela Tipo Licitação com descrição e código;
- Implementar tela Controle de Licitação/Empenho;
  - Na tela Controle de Licitação/Empenho criar capa com os seguintes campos: Órgão Público, Data Emissão, Tipo Licitação, Número Licitação, Número Processo, campo livre com a descrição Unidade Atendida, Detalhe.
  - Criar grid Empenho.
  - Possibilitar inserir vários empenhos informando o Número do Empenho, Data Emissão, Valor Total(editável), Valor Atendido(atualizado pela venda), Saldo, criar Status (Ativo, Entregue e Baixado).
  - Criar grid Itens do Empenho
  - Possibilitar incluir vários itens nesse grid com os campos: Empenho(buscar nos empenhos cadastrados), Código, Descrição, Marca, Unidade(editável para tratar conversão), Quantidade, Valor Unitário(editável), Vlr Total, Qtde Entregue, Qtde Saldo, Disponibilizar campo livre Descrição no Empenho, o que for escrito nesse campo deverá substituir a descrição principal do item ao emitir a nota fiscal - Apresentar esse campo no grid do pedido de venda, Criar Status com as opções ativo, entregue e baixado.

- No pedido de venda ao selecionar o Cliente órgão público o sistema verificará os empenhos com saldos e listará para ser selecionado - somente um empenho pode ser selecionado - e ao clicar em ok todos os itens desse empenho que estiverem com a status Ativo serão incluídos no pedido.
- Ao receber o pedido o sistema deverá atualizar as informações no empenho com relação aos saldos. E caso um item seja totalmente entregue o status deverá ser setado como entregue. (Tratar os saldos caso o pedido seja estornado)
- Somente os itens com status ativo é que deverão ser inseridos no pedido.
- Não permitir alterar o status do item para entregue se o mesmo tiver saldo.
- Somente deverá aparecer na lista para seleção os empenhos com status ativo.
- Se o status do empenho for alterado para Baixado os itens com saldo desse empenho também deverão ser setados como baixados.
- Não permitir colocar o empenho com status Entregue se houver itens com status ativo.
- Na impressão da nota, nas observações imprimir o número do Processo e do Empenho.
- Criar aba Notas Fiscais na tela de empenho e vincular todas as notas emitidas com os campos: Data Emissão, Série, Número, Pessoa e Vlr Total.
- Criar aba Histórico para gerar os logs: Data emissão empenho; Alteração dos Status.

**Solicitante**
Sou Mais Saúde

**Comment by dziza** [comment]
Status na Capa
  - Pendente
  - Em Andamento
  - Entregue

Alterar p/ "Em andamento" quando qualquer item do empenho for entregue, e alterar p/ "Entregue" quando não tiver mais item a entregar.

**Comment by dziza** [comment]
crm_controle_empenho
  - id
  - numero
  - processo
  - cliente
  - data_emi
  - status (Pendente, Em Andamento, Finalizado)
  - tipo
  - nome (nome da unidade atendida. Ex.: Escola Estadual Paulinho Panda)
  - detalhe

crm_empenho
  - numero
  - data_emi
  - vlr_total (soma dos itens)
  - vlr_atendido (soma dos itens atendidos)
  - vlr_saldo
  - status (Pendente, Em Andamento, Finalizado)

crm_empenho_item
  - produto
  - nome (preencher com a descrição do produto e permitir editar)
  - unidade (preencher com a unidade do produto e permitir editar)
  - qtd_bruto
  - qtd_embalagem
  - qtd_total
  - vlr_preco
  - vlr_total
  - qtd_atendido
  - qtd_saldo
  - status (Pendente, Em Andamento, Entregue, Baixado)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3571083/script.txt)

**Comment by Parapinski** [comment]
[script.txt](https://github.com/udisoft/roadmap/files/3574442/script.txt)
